import slugsJson from "@/data/people-slugs.json";

/**
 * Readable people addresses (/people/peter, /people/james-son-of-zebedee), generated by scripts/build-people-slugs.py.
 * The page itself still works by person id (STEP Bible's "james-mat-4-21"); these two maps translate at the edges, and
 * the old id addresses forward to the readable one.
 */
const idBySlug = new Map<string, string>(Object.entries((slugsJson as { slugs: Record<string, string> }).slugs));
const slugById = new Map<string, string>([...idBySlug].map(([slug, id]) => [id, slug]));

/** The person id an address segment names: a readable slug, or already an id. */
export const personIdOf = (segment: string): string => idBySlug.get(segment) ?? segment;
/** The readable address segment for a person id, when there is one. */
export const slugOf = (id: string): string | undefined => slugById.get(id);
