import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {writeFileSync,readFileSync} from 'node:fs';
import {StationArt} from '../../src/components/stations/StationArt';
const arts=['preachers','scholars'].map(kind=>renderToStaticMarkup(React.createElement(StationArt,{kind})));
const captions=[['Clear lines · living details','Full contrast, brighter voice waves and a visible lens.'],['Signal & discovery','A stronger voice pulse; a scan crosses the shelf and marks discoveries.'],['From shelf to page','Voice and written notes connect; selected books lift and connect to the open page.']];
let cells='';
for(let row=0;row<3;row++)for(let col=0;col<2;col++){
 let overlay='';
 if(col===1&&row===1)overlay=`<svg class="overlay" viewBox="0 0 240 160" fill="none" aria-hidden="true"><g class="shelf-scan"><path d="M15 28V61"/><circle cx="15" cy="28" r="3"/></g>${[45,91,148,197].map((x,i)=>`<g class="lift-book" style="--i:${i}"><path d="M${x} 58V32h7v26m-5-20h3m-3 13h3"/><path class="research-thread" d="M${x+3} 29Q120 5 120 82"/><circle class="research-dot" cx="${x+3}" cy="24" r="2"/></g>`).join('')}</svg>`;
 if(col===0&&row===2)overlay='<svg class="overlay" viewBox="0 0 240 160" fill="none" aria-hidden="true"><g class="margin-note"><path d="M182 66h39v29h-39Zm6 8h22m-22 7h15M179 87l-20 12"/></g><g class="margin-note second"><path d="M17 77h36v26H17Zm6 7h24m-24 7h17M54 94l23 9"/></g></svg>';
 cells+=`<article class="sample v${row} c${col}" tabindex="0"><header><span>${String.fromCharCode(65+row)}${col+1}</span><h2>${captions[row][0]}</h2></header><div class="scene st-door-art">${arts[col]}${overlay}</div><p>${col===0?['Radiating voice and small moving stars.','Broader waves travel above the pulpit; the scene stays readable.','Notes rise beside the sermon, connected to the source book.'][row]:['Original scholar scene, with a stronger lens and flame.','A scan passes across the shelf; page findings light in sequence.','Clean individual books lift from the shelf, with dots above them.'][row]}</p><span class="hover-note">Hover or focus to animate</span></article>`;
}
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Teachers · artwork motion study</title><link rel="stylesheet" href="styles.css"></head><body><main><header class="intro"><a href="/mockups/">← Design gallery</a><div><p class="eyebrow">Teachers / Line-art motion study</p><button id="theme">Light / dark</button></div><h1>Clear drawings.<em> Visible motion.</em></h1><p>Columns compare the two Teachers categories. Rows compare three motion treatments. Hover any drawing, or switch on the loops to compare them together.</p><label class="play"><input type="checkbox" id="play"> Animate all variants</label></header><div class="column-heads"><h2>Preachers & authors</h2><h2>Scholars</h2></div><section class="grid">${cells}</section></main><script src="page.js"></script></body></html>`;
writeFileSync('design/teachers-art-motion/index.html',html);
writeFileSync('design/teachers-art-motion/base.css',readFileSync('src/components/stations/stations.css','utf8').replaceAll('a.st-door:is(:hover, :focus-visible)', ':is(.sample:hover,.sample:focus-visible,body.playing .sample)').replaceAll('a.st-door:hover', '.sample:hover'));
