import { Fragment, useEffect, useRef, useState, type CSSProperties } from "react";
import { Link, useLocation, useSearchParams } from "react-router-dom";
import { STUDY_BRANCHES, type BranchId } from "./collections";
import { WRITERS } from "./writers";
import { SubjectArt } from "./Artwork";
import { Icon, StudyLink } from "./shared";
import "./hub.css";
function Heading({ text }: {
    text: string;
}) { return <>{text.split(/(<br>|<em>.*?<\/em>)/).map((part, i) => <Fragment key={i}>{part === '<br>' ? <br /> : part.startsWith('<em>') ? <em>{part.slice(4, -5)}</em> : part}</Fragment>)}</>; }
const writerDirectory = [...WRITERS, { name: 'Isaiah', id: 'isaiah-2ki-19-2', books: ['Isaiah'] }, { name: 'John', id: 'john-son-of-zebedee', books: ['John', 'Letters', 'Revelation'] }];
export default function StudyBranch({ branch }: {
    branch: BranchId;
}) {
    const b = STUDY_BRANCHES[branch], [params, setParams] = useSearchParams(), location = useLocation();
    const asked = params.get('area'), a = b.areas.find(a => a.id === asked) ?? b.areas[0], e = a.featured;
    const [hover, setHover] = useState<string | null>(null), doors = useRef<(HTMLAnchorElement | null)[]>([]), collection = useRef<HTMLElement>(null);
    useEffect(() => { if (location.hash === '#writer-preview')
        document.getElementById('writer-preview')?.scrollIntoView({ block: 'start' }); }, [location.hash, a.id]);
    useEffect(() => { if (!matchMedia('(prefers-reduced-motion: reduce)').matches)
        collection.current?.animate([{ opacity: .3, transform: 'translateY(8px)' }, { opacity: 1, transform: 'translateY(0)' }], { duration: 250, easing: 'ease-out' }); }, [a.id, branch]);
    return <div className="study-experience" style={{ '--branch-tone': `var(--${b.tone})` } as CSSProperties}><div className="branch" id="branch-root">
 <header className="branch-intro"><nav className="branch-nav" aria-label="Study navigation"><StudyLink to="/study">← Study hub</StudyLink><StudyLink className="other-branch" to={`/study/${b.other}`}>{STUDY_BRANCHES[b.other].label}<Icon name="arrowUp"/></StudyLink></nav><p className="eyebrow">{b.label} · {b.kicker}</p><h1><Heading text={b.heading}/></h1><p>{b.lead}</p></header>
 <section className="subject-landing" aria-labelledby="subject-title"><div className="subject-rule"><h2 id="subject-title">Choose a subject</h2><span>Open a collection. Find your next study.</span></div><div className="subject-doors" role="group" aria-label="Study subjects">{b.areas.map((area, i) => <Link key={area.id} ref={el => { doors.current[i] = el; }} className={`subject-door ${area.id === a.id ? 'selected' : ''}`} id={`door-${area.id}`} to={`?area=${area.id}`} data-area={area.id} style={{ '--tone': `var(--${area.tone})` } as CSSProperties} aria-expanded={a.id === area.id} aria-controls="subject-collection" onClick={event => { if (event.ctrlKey || event.metaKey || event.shiftKey || event.altKey || event.button !== 0)
        return; event.preventDefault(); const next = new URLSearchParams(params); next.set('area', area.id); setParams(next); }} onPointerEnter={() => setHover(area.id)} onPointerLeave={() => setHover(null)} onFocus={() => setHover(area.id)} onBlur={() => setHover(null)} onKeyDown={event => { const next = event.key === 'ArrowRight' ? (i + 1) % b.areas.length : event.key === 'ArrowLeft' ? (i + b.areas.length - 1) % b.areas.length : event.key === 'Home' ? 0 : event.key === 'End' ? b.areas.length - 1 : null; if (next !== null) {
        event.preventDefault();
        doors.current[next]?.focus();
    } }}><span className="subject-number">0{i + 1}</span><SubjectArt kind={area.art}/><strong>{area.title}</strong><span className="door-indicator" aria-hidden>↓</span></Link>)}</div><div className="subject-hint" aria-live="polite">{b.areas.map(area => <p key={area.id} className={(hover ?? a.id) === area.id ? 'visible' : ''}>{area.hint}</p>)}</div></section>
 {asked && asked !== a.id && <p id="selection-notice" role="status">That subject is not in this collection. Showing {a.title}.</p>}
 <section ref={collection} className="subject-collection" id="subject-collection" aria-labelledby="collection-title" style={{ '--tone': `var(--${a.tone})` } as CSSProperties}><div className="collection-intro"><p className="eyebrow">{a.title}</p><h2 id="collection-title"><Heading text={a.heading}/></h2><p>{a.intro}</p><div className="collection-method"><span>Begin</span><i /><span>Explore</span><i /><span>Connect</span></div></div><div className="collection-readings"><p className="reading-label">A place to begin</p><StudyLink className="featured-reading" to={e.href}><div className="featured-art"><SubjectArt kind={e.art ?? a.art}/></div><div><small>{e.kind}</small><h3>{e.title}</h3><p>{e.text}</p><span className="reading-meta">{e.meta}</span><span className="reading-action">{e.kind === 'Collection' ? 'Explore the collection' : e.kind === 'Question' ? 'Explore the question' : 'Open the guide'}<Icon name="arrowUp"/></span></div></StudyLink><div className="reading-list"><h3>{a.group}</h3>{a.items.map((item, i) => <StudyLink key={item.href} className="reading-row" to={item.href}><span className="reading-n">0{i + 1}</span><div><small>{item.kind}</small><h4>{item.title}</h4><p>{item.text}</p></div><Icon name="arrowUp"/></StudyLink>)}</div><div className="support-links"><span>Useful connections</span><div>{a.support.map(([title, href]) => <StudyLink key={href} to={href}>{title}<Icon name="arrowUp"/></StudyLink>)}</div></div></div>
 {a.writers && <section className="writer-preview" id="writer-preview" aria-labelledby="writers-title"><div><p className="eyebrow">Writers of Scripture</p><h3 id="writers-title">Begin with a life.<br /><em>Follow it into a book.</em></h3><p>These links open existing person pages. Book associations follow traditional attribution; individual books may be anonymous, disputed or associated with more than one contributor.</p></div><div className="writer-preview-list">{writerDirectory.map(w => <StudyLink key={w.id} to={`/people/${w.id}`}><span className="writer-monogram">{w.name[0]}</span><span><strong>{w.name}</strong><small>{w.books.join(' · ')}</small></span><Icon name="arrowUp"/></StudyLink>)}</div></section>}
 {a.planned && <div className="planned-note"><span className="eyebrow">Studies taking shape</span><p>{a.planned.join(' · ')}</p><small>These subjects have outlines; full studies are still to come.</small></div>}</section>
 {branch === 'academic' && <section className="reading-room" id="reading-guide"><div><p className="eyebrow">Before you follow a source</p><h2>Know what<br /><em>you’re reading.</em></h2><p>A surviving text, a modern edition and an interpretation each answer a different question.</p></div><div className="reading-steps">{[['Identify the witness', 'Who made it, when, and for what purpose? Distinguish the ancient work from the copy or edition before you.'], ['Read the context', 'Follow the passage, its genre and the source’s own perspective. A royal inscription speaks with a royal purpose.'], ['Consider the limits', 'Separate what survives from the conclusions drawn from it. Compare interpretations and their supporting evidence.']].map(([title, text], i) => <article key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}<StudyLink to="/apologetics/sources">Explore the source room<Icon name="arrowUp"/></StudyLink></div></section>}
 <div className="branch-bridge"><div><p className="eyebrow">Continue through Study</p><h2>{b.otherLine}</h2></div><StudyLink to={`/study/${b.other}`}>Explore {STUDY_BRANCHES[b.other].label}<Icon name="arrowUp"/></StudyLink></div></div></div>;
}
