const $ = (id) => document.getElementById(id);
const labels = { bible:'Scripture', bible_note:'Edition notes & headings', guide:'Guides & source records', authored_document:'Authored documents', reference:'Reference books', person:'People', place:'Places', study:'Study datasets', project_document:'Project documentation' };
const languageNames = {en:'English', hbo:'Hebrew', grc:'Greek', la:'Latin', es:'Spanish', fr:'French', de:'German', ar:'Arabic', zh:'Chinese', hi:'Hindi', pt:'Portuguese', ru:'Russian', ja:'Japanese', vi:'Vietnamese', fa:'Persian', it:'Italian'};
Object.assign(labels, {library_text:'Library texts', library_catalog:'Library catalog', library_review:'Library editions awaiting review'});
let documentId='', documentOffset=0, requestId=0;
function element(tag, text, className){ const node=document.createElement(tag); if(text!==undefined)node.textContent=text; if(className)node.className=className; return node; }
async function json(url){const response=await fetch(url);const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}
function option(select,value,title){const item=element('option',title);item.value=value;select.append(item);}
async function refreshStatus(initial=false){
  try{const data=await json('/api/status');if(data.state!=='ready'){$('message').textContent='The corpus has not been built yet.';return;}
    if(initial){$('stats').replaceChildren();for(const [value,title] of [[data.corpus.editions,'Bible editions'],[data.corpus.counts.verses,'Verse records'],[data.corpus.counts.documents,'Books & documents'],[data.corpus.counts.edges,'Recorded connections']]){const stat=element('div',undefined,'stat');stat.append(element('strong',value.toLocaleString()),element('span',title));$('stats').append(stat);}
      data.kinds.forEach(kind=>option($('kind'),kind,labels[kind]||kind));data.editions.forEach(item=>option($('edition'),item.edition,item.edition.toUpperCase()));[...new Set(data.editions.map(x=>x.language))].sort().forEach(lang=>option($('language'),lang,languageNames[lang]||lang));
      $('coverage').replaceChildren(...data.corpus.by_kind.map(item=>element('span',`${labels[item.kind]||item.kind}: ${item.count.toLocaleString()} passages`)));
    }
    const p=data.embeddings;const indexed=p.indexed||0;const total=data.corpus.counts.chunks;
    const progressLabel={running:'Preparing meaning search',needs_refresh:'Preparing the updated collection',not_started:'Meaning search has not started',stalled:'Meaning search preparation is waiting',interrupted:'Meaning search preparation was interrupted',partial:'Meaning search is partially prepared',optimizing:'Finishing meaning search'}[p.state]||'Preparing meaning search';
    $('progress').textContent=p.state==='complete'&&indexed===total?`Full-text and semantic indexes ready · ${total.toLocaleString()} searchable passages · all processing stays on this PC.`:`Full-text search is ready · ${p.state==='waiting_for_gpu'?'Waiting for GPU memory; preparation resumes automatically':progressLabel}: ${indexed.toLocaleString()} / ${total.toLocaleString()} passages (${(100*indexed/total).toFixed(1)}%). Meaning results cover the prepared portion so far.`;
  }catch(error){$('progress').textContent=error.message;}
}
function addConnections(parent,edges){const links=element('div',undefined,'connection-links');for(const edge of edges.slice(0,12)){const parts=edge.object.split(':');const ref=parts.length===5?`${parts[2]} ${parts[3]}:${parts[4]}`:edge.object;const button=element('button',ref);button.type='button';button.addEventListener('click',()=>{$('query').value=ref;$('edition').value='kjv';$('kind').value='';runSearch();});links.append(button);}if(links.childNodes.length){parent.append(element('h3','Recorded cross-references'),links,element('small','OpenBible.info · CC-BY · References invite examination in context.'));}}
function showReference(ref){$('reference').replaceChildren();$('reference').hidden=!ref?.verses?.length;if($('reference').hidden)return;
  $('reference').append(element('h2',`${ref.book} · ${ref.edition.toUpperCase()}`),element('p',ref.verses.map(v=>`${v.chapter}:${v.label} ${v.text}`).join('\n')));
  addConnections($('reference'),ref.connections?.outgoing||[]);
  if(ref.referencing_documents?.length){const details=element('details');details.append(element('summary',`${ref.referencing_documents.length} library documents cite this passage`));for(const doc of ref.referencing_documents){const button=element('button',doc.title);button.addEventListener('click',()=>openDocument(doc.id));const row=element('p');row.append(button);details.append(row);}$('reference').append(details);}
}
async function runSearch(){
  const id=++requestId;const params=new URLSearchParams(new FormData($('search')));if(!params.get('q')?.trim())return;
  $('message').textContent=params.get('mode')==='lexical'?'Searching the words…':'Searching the words and ideas…';$('results').setAttribute('aria-busy','true');
  history.replaceState(null,'','/?'+params);
  try{const data=await json('/api/search?'+params);if(id!==requestId)return;
    $('message').textContent=`${data.results.length} results · ${data.seconds.toFixed(2)} seconds`+(data.notices.length?'\n'+data.notices.join('\n'):'');showReference(data.reference);$('results').replaceChildren();
    for(const result of data.results){const article=element('article',undefined,'result');const meta=element('div',undefined,'result-meta');meta.append(element('span',labels[result.kind]||result.kind),element('span',result.methods.join(' + ')));article.append(meta,element('h2',result.title));const excerpt=element('p',result.text,'excerpt');excerpt.dir='auto';article.append(excerpt,element('p',result.source.licence,'source'));const nav=element('nav');const button=element('button','Read source context');button.type='button';button.addEventListener('click',()=>openDocument(result.document_id,result.id));nav.append(button);if(result.url){const link=element('a',result.kind==='bible'?'Read chapter ↗':'Open in Bible Project ↗');link.href=result.url;link.target='_blank';link.rel='noreferrer';nav.append(link);}article.append(nav);$('results').append(article);}
    if(!data.results.length)$('results').append(element('p','No matching passages in the selected collection. Try different words or broaden the filters.'));
  }catch(error){if(id===requestId)$('message').textContent=error.message;}finally{if(id===requestId)$('results').removeAttribute('aria-busy');}
}
async function openDocument(id,chunk){documentId=id;documentOffset=0;$('document-content').replaceChildren(element('p','Loading source context…'));$('more-document').hidden=true;if(!$('document').open)$('document').showModal();try{const data=await json('/api/document?'+new URLSearchParams({id,chunk:chunk||''}));$('document-title').textContent=data.document.title;$('document-content').replaceChildren(element('p',`${data.document.licence}\n${data.document.source}`,'source'));appendDocument(data);if(data.connections.outgoing.length){const relationships=element('div',undefined,'connection-links');for(const edge of data.connections.outgoing){const button=element('button',`${edge.relation}: ${edge.object.replace('person:','')}`);button.addEventListener('click',()=>openDocument(edge.object));relationships.append(button);}$('document-content').prepend(relationships);}}catch(error){$('document-content').textContent=error.message;}}
function appendDocument(data){for(const chunk of data.chunks){const article=element('article');const body=element('p',chunk.text);body.dir='auto';article.append(element('h3',chunk.locator),body);$('document-content').append(article);}documentOffset=data.offset+data.chunks.length;$('more-document').hidden=!data.more;}
$('more-document').addEventListener('click',async()=>{try{appendDocument(await json('/api/document?'+new URLSearchParams({id:documentId,offset:documentOffset})));}catch(error){$('document-content').append(element('p',error.message));}});
$('close-document').addEventListener('click',()=>$('document').close());
$('search').addEventListener('submit',event=>{event.preventDefault();runSearch();});
document.querySelectorAll('[data-query]').forEach(button=>button.addEventListener('click',()=>{$('query').value=button.dataset.query;$('kind').value=button.dataset.kind||'';runSearch();}));
async function init(){await refreshStatus(true);const params=new URLSearchParams(location.search);for(const key of ['q','kind','edition','language']){const control=$('search').elements.namedItem(key);if(control&&params.has(key))control.value=params.get(key);}const mode=params.get('mode');if(['lexical','semantic','hybrid'].includes(mode))$('search').elements.namedItem('mode').value=mode;if(params.get('q'))runSearch();setInterval(()=>refreshStatus(),15000);}init();
