const $=id=>document.getElementById(id);
function el(tag,attrs={},...children){const node=document.createElement(tag);for(const[key,value]of Object.entries(attrs)){if(key==='class')node.className=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2).toLowerCase(),value);else if(value!==undefined&&value!==false)node.setAttribute(key,value===true?'':String(value));}for(const child of children.flat(Infinity)){if(child!==null&&child!==undefined)node.append(child instanceof Node?child:document.createTextNode(String(child)));}return node;}
function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS(svg.namespaceURI,'use');svg.setAttribute('class','icon');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.5');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');use.setAttribute('href',`icons.svg#${name}`);svg.append(use);return svg;}
const directions={a:{name:'Compact ledger',description:'One framed ledger. Clear labels, counts and populations on a single line.'},b:{name:'Colour rows',description:'Quiet colour bands make each engagement category easy to find.'},c:{name:'Status cards',description:'Three compact cards give every category its own place.'},d:{name:'Ring & ledger',description:'See the share of groups at a glance, with the figures beside it.'}};
const labels={unengaged:'Unengaged and unreached',engagedUnreached:'Engaged yet unreached',noLongerUnreached:'No longer unreached'};
const keys=Object.keys(labels),compact=n=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n),number=n=>new Intl.NumberFormat('en').format(n);
const params=new URLSearchParams(location.search),requested=params.get('country');
let direction=params.get('d') in directions?params.get('d'):'a',comparing=params.get('compare')==='1';
const panels=new Map(Object.keys(directions).map(key=>[key,params.get('panel')==='groups'?'groups':'gospel'])),groupCache=new Map();
const response=await fetch('summary.json');if(!response.ok)throw Error('Country summaries unavailable.');
const snapshot=await response.json(),countries=snapshot.countries;
let country=countries.find(c=>c.code===requested)||countries.find(c=>c.code==='EGY');
const mapResponse=await fetch('globe.svg');if(mapResponse.ok){const parsed=new DOMParser().parseFromString(await mapResponse.text(),'image/svg+xml');$('globe-art').append(document.importNode(parsed.documentElement,true));for(const path of $('globe-art').querySelectorAll('.selectable'))path.addEventListener('click',()=>choose(path.dataset.country));}
$('search-icon').append(icon('search'));$('globe-icon').append(icon('globe'));
function syncUrl(){const next=new URLSearchParams();next.set('d',direction);next.set('country',country.code);if(comparing)next.set('compare','1');if(panels.get(direction)==='groups')next.set('panel','groups');history.replaceState(null,'',`?${next}`);}
function themeIcon(){$('theme').replaceChildren(icon(document.documentElement.dataset.theme==='dark'?'sun':'moon'));}
$('theme').addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('bp-theme',theme);}catch{}themeIcon();});themeIcon();
function flag(c){return el('img',{src:`/assets/muslim-world/flags/${c.code}.svg`,alt:c.code==='MYT'?'French flag for Mayotte':`${c.name} flag`,width:44,height:33});}
function countrySummary(){const religions=Object.entries(country.religions2020).filter(([name,share])=>name!=='Muslims'&&share>=.1).sort((a,b)=>b[1]-a[1]).map(([name,share])=>`${name==='Christians'?'Christian':name} ${share.toFixed(1)}%`).join(' · ');
 $('country-summary').replaceChildren(el('div',{class:'identity'},flag(country),el('div',{},el('span',{class:'region'},country.region),el('h2',{},country.name))),el('div',{class:'country-stat'},el('strong',{},compact(country.population2020)),el('span',{},'Population · 2020 estimate')),el('div',{class:'country-stat'},el('strong',{},country.muslimShare2020.toFixed(1),el('small',{},'%')),el('span',{},'Identify as Muslim · 2020'),el('span',{class:'religions'},religions||'Other categories below 0.1%')));
 $('source-link').href=`https://peoplegroups.org/country/${country.code}/`;for(const path of $('globe-art').querySelectorAll('.country'))path.classList.toggle('selected',path.dataset.country===country.code);
}
function choose(code){const next=countries.find(c=>c.code===code);if(!next)return;country=next;$('country-search').value='';$('country-results').hidden=true;$('country-search').setAttribute('aria-expanded','false');$('clear-country').hidden=true;countrySummary();render();syncUrl();}
function searchCountries(){const query=$('country-search').value.trim().toLowerCase(),results=$('country-results');$('clear-country').hidden=!query;results.hidden=!query;$('country-search').setAttribute('aria-expanded',String(!!query));results.replaceChildren();if(!query)return;const matches=countries.filter(c=>c.name.toLowerCase().includes(query));results.append(...matches.map(c=>el('button',{type:'button',onClick:()=>choose(c.code)},el('span',{},c.name),flag(c))));if(!matches.length)results.append(el('p',{role:'status'},'No countries match this search.'));}
$('country-search').addEventListener('input',searchCountries);$('clear-country').addEventListener('click',()=>{$('country-search').value='';searchCountries();$('country-search').focus();});
$('country-search').addEventListener('keydown',event=>{if(event.key==='Escape'){$('country-results').hidden=true;$('country-search').setAttribute('aria-expanded','false');}if(event.key==='ArrowDown'){event.preventDefault();$('country-results').querySelector('button')?.focus();}if(event.key==='Enter'){const match=countries.find(c=>c.name.toLowerCase().includes($('country-search').value.trim().toLowerCase()));if(match)choose(match.code);}});
$('country-results').addEventListener('keydown',event=>{const buttons=[...$('country-results').querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();buttons[(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}if(event.key==='Escape'){$('country-results').hidden=true;$('country-search').focus();}});
document.addEventListener('click',event=>{if(!event.target.closest('.finder')){$('country-results').hidden=true;$('country-search').setAttribute('aria-expanded','false');}});
function statusBar(){return el('div',{class:'status-bar','aria-hidden':'true'},keys.map(key=>el('span',{class:`status-${key}`,style:`width:${country.imb[key].groups/country.imb.totalGroups*100}%`})))}
function rows(){return el('div',{class:'engagement-rows'},keys.map(key=>el('div',{class:`engagement-row status-${key}`},el('div',{class:'engagement-title'},icon(key),el('span',{},labels[key])),el('div',{class:'engagement-value'},el('strong',{},country.imb[key].groups),el('span',{},`${compact(country.imb[key].population)} people`)))))}
function tiles(){return el('div',{class:'status-tiles'},keys.map(key=>el('div',{class:`status-tile status-${key}`},icon(key),el('strong',{},country.imb[key].groups),el('h4',{},labels[key]),el('p',{},`${compact(country.imb[key].population)} people`),el('div',{class:'tile-bar','aria-hidden':'true'},el('span',{style:`width:${country.imb[key].groups/country.imb.totalGroups*100}%`})))))}
function ring(){const host=el('div',{class:'ring'}),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 120 120');svg.setAttribute('aria-hidden','true');let offset=0;const perimeter=2*Math.PI*48;for(const key of keys){const length=country.imb[key].groups/country.imb.totalGroups*perimeter,circle=document.createElementNS(svg.namespaceURI,'circle');for(const[name,value]of Object.entries({cx:60,cy:60,r:48,class:`segment status-${key}`,'stroke-dasharray':`${Math.max(0,length-1.5)} ${perimeter}`,'stroke-dashoffset':-offset}))circle.setAttribute(name,String(value));svg.append(circle);offset+=length;}host.append(svg,el('div',{class:'ring-center'},el('strong',{},country.imb.totalGroups),el('span',{},'people groups')));return el('div',{class:'ring-summary'},host,rows());}
function overview(key){return el('div',{},el('div',{class:'overview-heading'},el('b',{},'Gospel presence / IMB'),el('span',{},`${country.imb.totalGroups} groups`)),key==='d'?ring():[statusBar(),key==='c'?tiles():rows()]);}
async function groupsView(host,c){host.append(el('p',{class:'loading',role:'status'},'Opening the people groups…'));try{if(!groupCache.has(c.code))groupCache.set(c.code,fetch(`/assets/muslim-world/people-groups/${c.code}.json`).then(async response=>{if(!response.ok)throw Error();const data=await response.json();if(data.country!==c.code||data.snapshotDate!==snapshot.snapshotDate||data.groups.length!==c.imb.totalGroups)throw Error();return data;}).catch(error=>{groupCache.delete(c.code);throw error;}));const data=await groupCache.get(c.code);if(!host.isConnected||country.code!==c.code)return;host.replaceChildren();const search=el('input',{type:'search',placeholder:'Name, language or religion','aria-label':'Search people groups'}),filter=el('select',{'aria-label':'Filter by engagement'},el('option',{value:'all'},'All engagement'),keys.map(key=>el('option',{value:key},labels[key]))),count=el('p',{class:'group-results',role:'status'}),scroll=el('div',{class:'group-scroll',tabindex:'0',role:'region','aria-label':`${c.name} people groups`});
 host.append(el('div',{class:'group-tools'},el('label',{},icon('search'),search),filter),count,scroll);
 function draw(){const query=search.value.trim().toLowerCase(),matches=data.groups.filter(group=>(filter.value==='all'||group.status===filter.value)&&`${group.name} ${group.language||''} ${group.religion}`.toLowerCase().includes(query));count.textContent=`${matches.length===data.groups.length?'All ':''}${matches.length}${matches.length===data.groups.length?'':` of ${data.groups.length}`} recorded groups`;const table=el('table',{class:'group-table'},el('thead',{},el('tr',{},['People group','Population','Engagement'].map(text=>el('th',{scope:'col'},text)))),el('tbody',{},matches.map(group=>el('tr',{class:`status-${group.status}`},el('td',{},el('a',{href:`https://peoplegroups.org/people_groups/${group.id.toLowerCase()}/`,target:'_blank',rel:'noreferrer'},group.name),el('small',{},`${group.language||'Language not reported'} · ${group.religion.replace('Islam - ','')}`)),el('td',{},number(group.population)),el('td',{},el('span',{class:`group-status status-${group.status}`},labels[group.status]))))));scroll.replaceChildren(table);if(!matches.length)scroll.append(el('p',{class:'group-empty'},'No matching groups.'));}search.addEventListener('input',draw);filter.addEventListener('change',draw);draw();}catch{if(host.isConnected)host.replaceChildren(el('p',{class:'loading',role:'status'},'The table could not be loaded. ',el('a',{href:`https://peoplegroups.org/country/${c.code}/`,target:'_blank',rel:'noreferrer'},'Read the IMB profile ↗')));}}
function card(key){const groupTab=panels.get(key)==='groups',card=el('article',{class:`country-card direction-${key}`,'aria-label':`${directions[key].name} country panel`}),body=el('div',{class:'card-body',role:'tabpanel',id:`body-${key}`,'aria-labelledby':`${key}-${groupTab?'groups':'gospel'}`});const tabs=el('div',{class:'card-tabs',role:'tablist','aria-label':`${directions[key].name} views`});for(const[id,name]of[['gospel','Gospel Presence'],['groups','People Groups']])tabs.append(el('button',{type:'button',role:'tab',id:`${key}-${id}`,'aria-selected':String(panels.get(key)===id),'aria-controls':`body-${key}`,tabindex:panels.get(key)===id?'0':'-1',onClick:()=>{panels.set(key,id);render();syncUrl();document.getElementById(`${key}-${id}`)?.focus();},onKeydown:event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?'gospel':event.key==='End'?'groups':id==='gospel'?'groups':'gospel';panels.set(key,next);render();syncUrl();document.getElementById(`${key}-${next}`)?.focus();}}},icon(id),name,id==='groups'?el('span',{class:'tab-count'},country.imb.totalGroups):null));
 card.append(tabs,body,el('div',{class:'card-foot'},el('span',{},'All recorded groups · 9 Oct 2026'),el('a',{href:`https://peoplegroups.org/country/${country.code}/`,target:'_blank',rel:'noreferrer'},'Source',icon('arrow'))));if(groupTab)queueMicrotask(()=>groupsView(body,country));else body.append(overview(key));return card;}
function render(){for(const button of document.querySelectorAll('[data-direction]'))button.setAttribute('aria-pressed',String(!comparing&&button.dataset.direction===direction));$('compare').setAttribute('aria-pressed',String(comparing));document.querySelector('.atlas').classList.toggle('is-comparing',comparing);$('comparison').hidden=!comparing;$('comparison').replaceChildren();$('active-panel').replaceChildren();if(comparing){for(const[key,value]of Object.entries(directions))$('comparison').append(el('section',{},el('h3',{class:'compare-heading'},el('b',{},key.toUpperCase()),el('span',{},value.name)),card(key)));}else{$('direction-label').textContent=`${direction.toUpperCase()} / ${directions[direction].name}`;$('direction-description').textContent=directions[direction].description;$('active-panel').append(card(direction));}}
for(const button of document.querySelectorAll('[data-direction]'))button.addEventListener('click',()=>{direction=button.dataset.direction;comparing=false;render();syncUrl();});$('compare').addEventListener('click',()=>{comparing=!comparing;render();syncUrl();});
countrySummary();render();syncUrl();
