import { ArrowRight, ArrowUpRight, BookOpen, Bookmark, Check, CheckCircle2, Compass, GitBranch, HeartHandshake, Library, ListFilter, MessageCircle, Route as RouteIcon, Search, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes, useLocation, useParams, useSearchParams } from "react-router-dom";
import { RefLink } from "@/components/study/StudyParts";
import { APOLOGETICS_ANCHOR, CONVERSATION_STEPS } from "@/data/apologetics";
import { AP_EDITORIAL, DEBATES, PATHS, PRACTICE, SOURCES, STUDIES, TOPICS, WORLDVIEWS, sourceById, studyById, studyMinutes, topicById } from "@/data/apologetics-library";
import { useApologeticsNotebook, type ApNotebook } from "@/lib/apologetics-notebook";
import { ApBack as Back, ApHeading as Heading, ApSectionHeading as SectionHeading, ApNote as Note, ApPassages, ApSearch, ApCitations, ApSourcePolicy, Constellation, PathCard, SourceLink, StudyCard, TopicArt } from "@/components/ApologeticsParts";
import { AP_BASE as base, apColor as color, studyUrl } from "@/lib/apologetics-links";
import { searchStudies, type StudyHit } from "@/lib/apologetics-search";
import { MeaningPrompt } from "@/components/search/MeaningPrompt";
import { preferMeaning } from "@/lib/meaning/store";
import { useMeaningResults } from "@/lib/meaning/useMeaningResults";
import ReformedLibraryPage, { ReformedDoor, HistoricReading } from "./ReformedLibraryPage";
import "./apologetics.css";
import { WorldviewIndex, WorldviewPage } from "./WorldviewsPage";

const destinations = [["", "Explore"], ["/questions", "Questions"], ["/topics/reformed", "Reformed theology"], ["/texts", "Historic texts"], ["/paths", "Learning paths"], ["/worldviews", "Worldviews"], ["/debates", "Debates"], ["/practice", "Practice"], ["/saved", "My study"]];
export default function ApologeticsPage() {
  const book = useApologeticsNotebook(), location = useLocation();
  useEffect(() => {
    const [, , section, id] = location.pathname.split("/");
    const title = section === "texts" ? "Historic Reformed texts" : section === "study" ? studyById(id)?.title : section === "topics" ? topicById(id)?.title : section === "paths" ? PATHS.find((path) => path.id === id)?.title : section === "worldviews" ? WORLDVIEWS.find((worldview) => worldview.id === id)?.title : section === "debates" ? DEBATES.find((debate) => debate.id === id)?.title : undefined;
    document.title = [title, "Apologetics", "Bible Project"].filter(Boolean).join(" · ");
    return () => { document.title = "Bible Project"; };
  }, [location.pathname]);
  const legacy: Record<string, string> = { "#foundations": "/paths/begin", "#conversation": "/practice", "#across-beliefs": "/worldviews", "#debates": "/debates" };
  if (location.pathname.replace(/\/$/, "") === base && legacy[location.hash]) return <Navigate replace to={base + legacy[location.hash]} />;
  return <div className="ap-page mx-auto max-w-7xl px-4 sm:px-6">
    <div className="ap-masthead"><Link to={base}><ShieldCheck size={17} /> Apologetics <span>Reason · Faith · Witness</span></Link><Link to={base + "/sources"}>The source room <ArrowUpRight size={14} /></Link></div>
    <nav className="ap-navigation" aria-label="Apologetics library">{destinations.map(([path, label]) => <NavLink key={path} to={base + path} end={!path}>{label}{path === "/saved" && book.notebook.saved.length > 0 && <span>{book.notebook.saved.length}</span>}</NavLink>)}</nav>
    {book.storageError && <p className="ap-storage-error" role="status">Your browser could not save these changes. Keep this tab open and copy any notes you want to retain.</p>}
    <Routes>
      <Route index element={<Hub book={book} />} /><Route path="texts" element={<ReformedLibraryPage />} /><Route path="reformed" element={<Navigate replace to={base + "/topics/reformed"} />} /><Route path="questions" element={<QuestionLibrary book={book} />} /><Route path="topics/:id" element={<TopicPage book={book} />} /><Route path="study/:id" element={<StudyPage book={book} />} /><Route path="paths" element={<PathIndex book={book} />} /><Route path="paths/:id" element={<PathPage book={book} />} /><Route path="worldviews" element={<WorldviewIndex />} /><Route path="worldviews/:id" element={<WorldviewPage book={book} />} /><Route path="debates" element={<DebateIndex />} /><Route path="debates/:id" element={<DebatePage book={book} />} /><Route path="practice" element={<PracticePage key={location.search} book={book} />} /><Route path="sources" element={<SourceRoom />} /><Route path="saved" element={<SavedPage book={book} />} /><Route path="*" element={<Missing />} />
    </Routes>
    <footer className="ap-footer"><div><BookOpen size={20} /><p><strong>{AP_EDITORIAL.footerTitle}</strong><span>{AP_EDITORIAL.footerText}</span></p></div><RefLink span={APOLOGETICS_ANCHOR} label="Our starting point · 1 Peter 3:15–16" /></footer>
  </div>;
}
function Hub({ book }: { book: ApNotebook }) {
  const [query, setQuery] = useState(""); const next = PATHS[0].studies.find((id) => !book.notebook.read.includes(id)) ?? PATHS[0].studies[0];
  return <>
    <header className="ap-universe-hero"><div><p className="ap-eyebrow"><span /> A connected library of Christian thought</p><h1>A reason for <br /><em>the hope.</em></h1><p>Bring your hardest questions.<br />Follow the evidence. Know the faith.<br />Carry it into a real conversation.</p><div className="ap-hero-actions"><Link className="ap-button ap-button-solid" to={base + "/paths/begin"}>Find your starting point <ArrowRight size={16} /></Link><Link to={base + "/questions"}>Explore every question <ArrowUpRight size={14} /></Link></div><div className="ap-library-count"><span><strong>{STUDIES.length}</strong> studies</span><span><strong>{TOPICS.length}</strong> connected fields</span><span><strong>{PATHS.length}</strong> learning paths</span></div></div><Constellation /></header>
    <form className="ap-search-door" action={base + "/questions"} onSubmit={(event) => { if (!query.trim()) event.preventDefault(); }}><Search size={23} /><label htmlFor="ap-home-search" className="sr-only">Find an apologetics question</label><input id="ap-home-search" type="search" name="q" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="What are you wrestling with? Try suffering, Islam, or the resurrection…" /><button type="submit" aria-label="Search apologetics"><ArrowRight size={21} /></button></form>
    <MeaningPrompt query={query} className="ap-meaning-prompt" active={<span>Meaning search is on: questions in the library are ranked by what you mean.</span>} />
    <ApSourcePolicy compact /><section className="ap-section"><SectionHeading eyebrow="Connected fields. A shared foundation." title="There is more to explore." to={base + "/questions"} link="The question library" /><div className="ap-topic-grid">{TOPICS.map((topic, i) => <Link key={topic.id} to={topic.id === "worldviews" ? base + "/worldviews" : base + "/topics/" + topic.id} className={"ap-topic-card" + (topic.id === "reformed" ? " ap-topic-reformed" : "")} style={color(topic.color)}><div><span className="ap-card-index">0{i + 1} / {STUDIES.filter((study) => study.topic === topic.id).length} studies</span><ArrowUpRight size={17} /></div><TopicArt index={i} /><h3>{topic.title}</h3><p>{topic.description}</p><span className="ap-card-question">{topic.question}</span></Link>)}</div></section>
    <section className="ap-section"><SectionHeading eyebrow="A route through the questions" title="Start where you are." to={base + "/paths"} link="All learning paths" /><div className="ap-path-grid">{PATHS.slice(0, 3).map((path, i) => <PathCard key={path.id} path={path} index={i} book={book} />)}</div></section>
    <section className="ap-spotlight" style={color("prophets")}><div className="ap-spotlight-art"><TopicArt index={4} /><span>Shared questions<br />Distinct convictions</span></div><div><p className="ap-eyebrow">Across beliefs / Featured collection</p><h2>Christianity<br /><em>& Islam.</em></h2><p>Who is Jesus? What does one God mean? What happened at the cross? Put the primary texts beside the questions, then examine the differences.</p><Link className="ap-button" to={base + "/worldviews/islam"}>Enter the collection <ArrowRight size={16} /></Link></div></section>
    <section className="ap-section"><SectionHeading eyebrow="From conviction to conversation" title="Read. Examine. Put it into practice." /><div className="ap-ecosystem-grid">{[{ title: "The debate room", icon: MessageCircle, text: "Three real exchanges, full transcripts and questions that help you follow the reasoning.", to: "/debates" }, { title: "The source room", icon: Library, text: "Open the manuscripts, confessions and religious texts behind the studies.", to: "/sources" }, { title: "Conversation practice", icon: HeartHandshake, text: "Try a response, consider the feedback and prepare your own words.", to: "/practice" }].map(({ title, icon: Icon, text, to }) => <Link key={to} to={base + to}><Icon size={23} strokeWidth={1.3} /><h3>{title}</h3><p>{text}</p><ArrowUpRight size={17} /></Link>)}</div></section>
    {book.notebook.read.length > 0 && <div className="ap-continue"><CheckCircle2 size={21} /><div><strong>Keep following the thread.</strong><p>{book.notebook.read.length} studies marked read on this device.</p></div><Link to={studyUrl(next)}>Continue your foundation <ArrowRight size={16} /></Link></div>}
  </>;
}
function QuestionLibrary({ book, topicId }: { book: ApNotebook; topicId?: string }) {
  const [params, setParams] = useSearchParams(), topic = topicId ? topicById(topicId) : undefined;
  const query = params.get("q") ?? "", filter = topic?.id ?? params.get("topic") ?? "all";
  const search = searchStudies(STUDIES, query);
  // Meaning search (when switched on) ranks the studies for a real question; "?by=words" keeps the word search.
  const meaning = useMeaningResults(query), question = preferMeaning(query), wordsOnly = params.get("by") === "words";
  const byMeaning = question && !wordsOnly && meaning.status === "done" && !!meaning.results;
  const meaningHits: StudyHit[] = byMeaning ? meaning.results!.studies.slice(0, 8).flatMap((s) => { const study = studyById(s.id); return study ? [{ study, snippet: null }] : []; }) : [];
  const visible = (byMeaning ? meaningHits : search.hits).filter((hit) => filter === "all" || hit.study.topic === filter);
  const change = (key: string, value: string) => { const next = new URLSearchParams(params); if (value && value !== "all") next.set(key, value); else next.delete(key); setParams(next, { replace: true }); };
  return <><Heading eyebrow={topic ? "Explore a field" : "The question library"} title={topic?.title ?? "A good question opens a door."} lead={topic?.description ?? "Find a starting answer, follow the argument, test an objection and open the sources."} />{topic?.id === "reformed" && <ReformedDoor />}<div className="ap-filter-bar"><ApSearch value={query} onChange={(value) => change("q", value)} /><p role="status">{visible.length} {visible.length === 1 ? "study" : "studies"}{byMeaning ? " · closest in meaning" : search.partial && visible.length > 0 && " · none has every word, so these have some"}</p></div>
    <MeaningPrompt query={query} className="ap-meaning-prompt" active={!query.trim() ? <span>Meaning search is on: ask a whole question and the studies are ranked by what you mean.</span> : !question ? <span>Meaning search is on: ask a whole question (three words or more) to rank by meaning.</span> : wordsOnly ? <button type="button" className="ap-text-button" onClick={() => change("by", "")}>Rank by meaning instead <ArrowRight size={13} /></button> : meaning.status === "loading" ? <span>Ranking the studies by meaning…</span> : <span>Ranked by meaning. <button type="button" className="ap-text-button" onClick={() => change("by", "words")}>Match the exact words instead</button></span>} />
    {!topic && <div className="ap-filter-chips" role="group" aria-label="Filter by topic"><button type="button" aria-pressed={filter === "all"} onClick={() => change("topic", "all")}><ListFilter size={14} />All questions</button>{TOPICS.map((item) => <button key={item.id} type="button" aria-pressed={filter === item.id} onClick={() => change("topic", item.id)}>{item.title}</button>)}</div>}
    {visible.length ? <div className="ap-study-grid">{visible.map((hit) => <StudyCard key={hit.study.id} study={hit.study} book={book} snippet={hit.snippet} />)}</div> : <div className="ap-empty"><Search size={26} /><h2>No studies match that search.</h2><p>Try a broader word or clear the filters.</p><button className="ap-button" onClick={() => setParams({})}>Clear search and filters</button></div>}
    {topic && <section className="ap-section"><SectionHeading eyebrow="Everything connects" title="Follow a neighbouring question." /><div className="ap-topic-links">{TOPICS.filter((item) => item.id !== topic.id).map((item) => <Link key={item.id} to={base + "/topics/" + item.id}>{item.title}<ArrowUpRight size={14} /></Link>)}</div></section>}
  </>;
}
function TopicPage({ book }: { book: ApNotebook }) { const { id = "" } = useParams(); return topicById(id) ? <QuestionLibrary key={id} topicId={id} book={book} /> : <Missing />; }
function StudyPage({ book }: { book: ApNotebook }) {
  const location = useLocation();
  const origin = location.state?.worldviewReturn;
  const collection = WORLDVIEWS.find(item => item.id === origin?.id);
  const question = collection?.rows.find(row => row.id === origin?.question);
  const { id = "" } = useParams(), study = studyById(id); if (!study) return <Missing />; const topic = topicById(study.topic)!;
  return <div key={id} style={color(topic.color)}><header className="ap-study-heading"><Back to={collection ? base + "/worldviews/" + collection.id + (question ? "?question=" + question.id : "") + "#comparison" : base + "/topics/" + topic.id}>{collection ? collection.title : topic.title}</Back><div className="ap-card-meta"><span>Study guide · {studyMinutes(study)} min read</span><button type="button" className="ap-save-label" aria-pressed={book.notebook.saved.includes(id)} onClick={() => book.toggle("saved", id)}><Bookmark size={15} />{book.notebook.saved.includes(id) ? "Saved to my study" : "Save study"}</button></div><h1>{study.title}</h1><p>{study.summary}</p></header>
    <div className="ap-study-layout"><article className="ap-article"><section id="answer" className="ap-answer"><p className="ap-eyebrow">The starting answer</p><p>{study.answer}</p><ApCitations citations={study.support.answer} /></section><section id="reasoning"><p className="ap-eyebrow">Follow the reasoning</p><h2>From the claim to the conclusion.</h2><ol className="ap-argument">{study.reasoning.map((step, index) => <li key={step}><span>0{index + 1}</span><div><p>{step}</p><ApCitations citations={study.support.reasoning[index]} /></div></li>)}</ol><div className="ap-conclusion"><GitBranch size={19} /><div><p>{study.conclusion}</p><ApCitations citations={study.support.conclusion} /></div></div></section>{study.sections.map((section, index) => <section key={section.title}><h2>{section.title}</h2><p>{section.body}</p><ApCitations citations={study.support.sections[index]} /></section>)}<section id="objection" className="ap-objection"><p className="ap-eyebrow">Take the objection seriously</p><h2>{study.objection}</h2><p>{study.reply}</p><ApCitations citations={study.support.reply} /><div className="ap-answer-limit"><strong>What this answer establishes—and what remains</strong><p>{study.limit}</p><ApCitations citations={study.support.limit} /></div></section><section id="conversation" className="ap-conversation-prompt"><MessageCircle size={22} /><div><p className="ap-eyebrow">Carry it into a conversation</p><blockquote>{study.prompt}</blockquote><ApCitations citations={study.support.prompt} label="Editorial application" /><Link to={base + "/practice"}>Practise a response <ArrowRight size={15} /></Link></div></section><HistoricReading studyId={id} /><Note id={id} prompt="What would you want to examine or ask next?" book={book} /><button type="button" className="ap-button ap-mark-read" aria-pressed={book.notebook.read.includes(id)} onClick={() => book.toggle("read", id)}><CheckCircle2 size={18} />{book.notebook.read.includes(id) ? "Marked as read" : "Mark this study as read"}</button></article>
    <aside className="ap-study-sidebar" aria-label="Study companion"><div className="ap-companion-inner"><p className="ap-eyebrow">In this study</p><nav aria-label="Study contents"><a href="#answer">The starting answer</a><a href="#reasoning">The reasoning</a><a href="#objection">The objection & reply</a><a href="#conversation">A conversation starter</a></nav><ApPassages key={id} study={study} /><a className="ap-text-button ap-document-download" href={"/content/apologetics/study-" + id + ".md"} download>Download this study <ArrowUpRight size={13} /></a>{study.sources.length > 0 && <div className="ap-study-sources"><p className="ap-eyebrow">Go to the source</p>{study.sources.map((source) => <SourceLink key={source} id={source} />)}</div>}<p className="ap-editorial-note">{AP_EDITORIAL.guideNote}</p><Link className="ap-text-button" to={base + "/sources"}>Read our doctrinal and source policy <ArrowUpRight size={13} /></Link></div></aside></div>
    <section className="ap-section"><SectionHeading eyebrow="Follow the connections" title="This question opens another." /><div className="ap-study-grid">{study.related.map((related) => <StudyCard key={related} study={studyById(related)!} book={book} />)}</div></section><div className="ap-topic-links">{PATHS.filter((path) => path.studies.includes(id)).map((path) => <Link key={path.id} to={base + "/paths/" + path.id}><RouteIcon size={15} />Continue in: {path.title}<ArrowRight size={15} /></Link>)}</div></div>;
}
function PathIndex({ book }: { book: ApNotebook }) { return <><Heading eyebrow="Guided learning" title="One question at a time." lead="A thoughtful order, connected studies and progress you can return to. Choose the route that meets you where you are." /><div className="ap-path-grid ap-path-grid-wide">{PATHS.map((path, index) => <PathCard key={path.id} path={path} index={index} book={book} />)}</div><p className="ap-local-note">Read status and reflections are kept on this device. No account is needed.</p></>; }
function PathPage({ book }: { book: ApNotebook }) { const { id } = useParams(), path = PATHS.find((item) => item.id === id); if (!path) return <Missing />; const count = path.studies.filter((item) => book.notebook.read.includes(item)).length, next = path.studies.find((item) => !book.notebook.read.includes(item)); return <><Heading eyebrow="A guided learning path" title={path.title} lead={path.description}><div className="ap-path-progress"><progress value={count} max={path.studies.length} aria-label="Path progress" /><span>{count} of {path.studies.length} read</span></div>{next && <Link className="ap-button ap-button-solid" to={studyUrl(next)}>{count ? "Continue the path" : "Begin the path"}<ArrowRight size={16} /></Link>}</Heading><ol className="ap-path-timeline">{path.studies.map((item, index) => { const study = studyById(item)!; return <li key={item}><span>{book.notebook.read.includes(item) ? <Check size={18} /> : String(index + 1).padStart(2, "0")}</span><Link to={studyUrl(item)}><p className="ap-eyebrow">{topicById(study.topic)!.title} · {studyMinutes(study)} min</p><h2>{study.title}</h2><p>{study.summary}</p><span>{book.notebook.read.includes(item) ? "Revisit study" : "Open study"}<ArrowRight size={15} /></span></Link></li>; })}</ol><Back to={base + "/paths"}>All learning paths</Back></>; }
function DebateIndex() { return <><Heading eyebrow="The debate room" title="Follow the argument. Not the applause." lead="Three sourced exchanges with full transcripts and a guide to the questions at stake. Read both speakers before reaching a verdict." /><div className="ap-debate-list">{DEBATES.map((debate, index) => <Link to={base + "/debates/" + debate.id} key={debate.id}><div className="ap-debate-mark"><span>0{index + 1}</span><MessageCircle size={38} strokeWidth={1} /></div><div><p className="ap-eyebrow">{debate.lens} · Transcript study</p><h2>{debate.title}</h2><strong>{debate.speakers}</strong><p>{debate.description}</p><small>{debate.setting}</small></div><ArrowUpRight size={22} /></Link>)}</div><p className="ap-local-note">{AP_EDITORIAL.debateIndexNote}</p></>; }
function DebatePage({ book }: { book: ApNotebook }) { const { id } = useParams(), debate = DEBATES.find((item) => item.id === id); if (!debate) return <Missing />; return <><Heading eyebrow={debate.lens + " / Debate study"} title={debate.title} lead={debate.description}><p className="ap-debate-credit">{debate.speakers}<br />{debate.setting}</p><a className="ap-button ap-button-solid" href={sourceById(debate.source).url} target="_blank" rel="noreferrer">Open the full transcript <ArrowUpRight size={16} /></a></Heading><div className="ap-debate-study"><section><p className="ap-eyebrow">The exchange</p><h2>What is being argued?</h2><p>{debate.claim}</p><ApCitations citations={debate.basis} label="Record of the exchange" /><div className="ap-conclusion"><Compass size={22} /><p>{debate.hinge}</p></div><h2>Read with these questions.</h2><ol>{debate.prompts.map((prompt) => <li key={prompt}>{prompt}</li>)}</ol><p className="ap-editorial-note">{AP_EDITORIAL.debateNote}</p></section><aside><SourceLink id={debate.source} /><p className="ap-editorial-note">{sourceById(debate.source).note}</p><Note id={"debate-" + debate.id} prompt="Which premise or source would you want to check?" book={book} /></aside></div><section className="ap-section"><SectionHeading eyebrow="Prepare before you debate" title="Study the questions underneath." /><div className="ap-study-grid">{debate.studies.map((study) => <StudyCard key={study} study={studyById(study)!} book={book} />)}</div></section></>; }
function PracticePage({ book }: { book: ApNotebook }) {
  const [scenarioParams, setScenarioParams] = useSearchParams(); const scenario = Math.max(0, PRACTICE.findIndex((entry) => entry.id === scenarioParams.get("scenario"))); const setScenario = (index: number) => setScenarioParams({ scenario: PRACTICE[index].id }, { replace: true }); const [choice, setChoice] = useState<number | null>(null), [step, setStep] = useState(0); const item = PRACTICE[scenario], conversation = CONVERSATION_STEPS[step];
  return <><Heading eyebrow="The conversation workshop" title="Truthful words. A human conversation." lead="Practise understanding the concern, choosing a first response and putting an answer into your own words." /><div className="ap-practice-tabs" role="group" aria-label="Choose a conversation">{PRACTICE.map((entry, index) => <button key={entry.id} type="button" aria-pressed={index === scenario} onClick={() => { setScenario(index); setChoice(null); }}>{entry.label}</button>)}</div><section className="ap-practice"><div><p className="ap-eyebrow">An imagined conversation</p><h2>{item.title}</h2><p>{item.context}</p><h3>{item.question}</h3><div className="ap-practice-options">{item.options.map((option, index) => <button type="button" key={option} aria-pressed={choice === index} onClick={() => setChoice(index)}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div>{choice !== null && <div className="ap-practice-feedback" role="status"><strong>{choice === item.best ? "A thoughtful place to begin." : "Consider a different first step."}</strong><p>{item.explanation}</p><ApCitations citations={item.basis} label="Basis for this application" /><Link to={studyUrl(item.study)}>Explore the underlying question <ArrowRight size={14} /></Link></div>}</div><aside><Note id={"practice-" + item.id} prompt={item.prompt} book={book} /><Link className="ap-button" to={studyUrl("conversation")}>A guide to Christian witness <ArrowUpRight size={15} /></Link></aside></section><section className="ap-section"><SectionHeading eyebrow="A rhythm to return to" title="Listen. Clarify. Give a reason. Invite." /><div className="ap-conversation"><div className="ap-steps" role="group" aria-label="Conversation steps">{CONVERSATION_STEPS.map((entry, index) => <button key={entry.title} type="button" aria-pressed={index === step} onClick={() => setStep(index)}><span>0{index + 1}</span>{entry.title}<ArrowRight size={15} /></button>)}</div><div className="ap-step-detail" aria-live="polite"><p className="ap-editorial-note">{AP_EDITORIAL.practiceNote}</p><h3>{conversation.line}</h3><p>{conversation.detail}</p><blockquote>{conversation.prompt}</blockquote><RefLink span={conversation.span} /></div></div></section></>;
}
function SourceRoom() { const [kind, setKind] = useState("All sources"), visible = SOURCES.filter((source) => kind === "All sources" || source.kind === kind); return <><Heading eyebrow="The source room" title="Go beyond the summary." lead={AP_EDITORIAL.sourceRoomIntro} /><ReformedDoor /><ApSourcePolicy /><div className="ap-document-downloads" aria-label="Download the apologetics library"><span>Take the library with you</span><a href="/content/apologetics/library.md" download>Study documents · Markdown <ArrowUpRight size={13} /></a><a href="/content/apologetics/library.json" download>Structured collection · JSON <ArrowUpRight size={13} /></a></div><div className="ap-filter-chips" role="group" aria-label="Source type">{["All sources", ...new Set(SOURCES.map((source) => source.kind))].map((value) => <button type="button" key={value} aria-pressed={kind === value} onClick={() => setKind(value)}>{value}</button>)}</div><p className="ap-local-note">{AP_EDITORIAL.sourceRoomNote}</p><div className="ap-source-room">{visible.map((source) => <article key={source.id}><SourceLink id={source.id} /><p>{source.note}</p><div className="ap-source-backlinks">{STUDIES.filter((study) => study.sources.includes(source.id)).map((study) => <Link key={study.id} to={studyUrl(study.id)}>{study.title}<ArrowUpRight size={12} /></Link>)}{DEBATES.filter((debate) => debate.source === source.id).map((debate) => <Link key={debate.id} to={base + "/debates/" + debate.id}>Study the exchange: {debate.title}<ArrowUpRight size={12} /></Link>)}</div></article>)}</div></>; }
function SavedPage({ book }: { book: ApNotebook }) { const saved = STUDIES.filter((study) => book.notebook.saved.includes(study.id)), read = STUDIES.filter((study) => book.notebook.read.includes(study.id)), notes = Object.entries(book.notebook.notes).filter(([, note]) => note.trim()); return <><Heading eyebrow="Your study desk" title="Keep the questions worth returning to." lead="Your saved studies, reading progress and reflections stay here on this device. No account or public profile is involved." /><div className="ap-desk-counts"><span><Bookmark size={18} />{saved.length} saved</span><span><CheckCircle2 size={18} />{read.length} read</span><span><MessageCircle size={18} />{notes.length} reflections</span></div>{saved.length ? <div className="ap-study-grid">{saved.map((study) => <StudyCard key={study.id} study={study} book={book} />)}</div> : <div className="ap-empty"><Bookmark size={27} /><h2>A place for your next question.</h2><p>Use the bookmark on any study to keep it here.</p><Link className="ap-button" to={base + "/questions"}>Find a study <ArrowRight size={15} /></Link></div>}{read.length > 0 && <section className="ap-section"><SectionHeading eyebrow="Your progress" title="Questions you have explored." /><div className="ap-topic-links">{read.map((study) => <Link key={study.id} to={studyUrl(study.id)}><Check size={15} />{study.title}<ArrowUpRight size={14} /></Link>)}</div></section>}{notes.length > 0 && <section className="ap-section"><SectionHeading eyebrow="Your own words" title="Reflections to return to." /><div className="ap-reflections">{notes.map(([id, note]) => { const study = studyById(id), debate = DEBATES.find((item) => "debate-" + item.id === id), practice = PRACTICE.find((item) => "practice-" + item.id === id), worldview = WORLDVIEWS.find((item) => "worldview-" + item.id === id); return <article key={id}><Link to={study ? studyUrl(id) : debate ? base + "/debates/" + debate.id : worldview ? base + "/worldviews/" + worldview.id : base + "/practice" + (practice ? "?scenario=" + practice.id : "")}><h3>{study?.title ?? debate?.title ?? worldview?.title ?? practice?.title ?? "Reflection"}</h3><ArrowUpRight size={15} /></Link><p>{note}</p></article>; })}</div></section>}</>; }
function Missing() { return <div className="ap-empty"><Compass size={30} /><h1>This study could not be found.</h1><p>Return to the library to follow another question.</p><Back /></div>; }
