import { ArrowRight, ArrowUpRight, BookOpen, Check, Route as RouteIcon } from 'lucide-react';
import { useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { WORLDVIEWS, studyById, studyMinutes } from '@/data/apologetics-library';
import { ApBack, ApCitations, ApNote, ApSectionHeading, SourceLink } from '@/components/ApologeticsParts';
import { AP_BASE as base, studyUrl } from '@/lib/apologetics-links';
import type { ApNotebook } from '@/lib/apologetics-notebook';
import './worldviews.css';

const identities: Record<string, { accent: string; theme: string; name: string }> = {
  islam: { accent: 'var(--poetry)', theme: 'Jesus · God · the cross', name: 'Islam' },
  secular: { accent: 'var(--epistles)', theme: 'Reason · morality · meaning', name: 'Secular thought' },
  buddhism: { accent: 'var(--accent)', theme: 'Suffering · self · release', name: 'Buddhism' },
  hinduism: { accent: 'var(--history)', theme: 'Self · action · refuge', name: 'Hinduism' },
};
// Decorative book/geometry motifs; these are not diagrams of a tradition's doctrine.
function CollectionArt({ id }: { id: string }) {
  return <svg className={'wv-art wv-art-' + id} viewBox="0 0 420 290" fill="none" aria-hidden="true">
    <circle cx="210" cy="138" r="110" strokeDasharray="1 9" opacity=".4" />
    {id === 'islam' ? <><path d="M115 239V121a95 95 0 0 1 190 0v118M135 239V121a75 75 0 0 1 150 0v118M155 239V126q0-43 55-74 55 31 55 74v113" /><path d="M155 214q27-12 55 0 28-12 55 0v-54q-28-12-55 0-28-12-55 0ZM210 160v54M166 177q18-5 33 0m-33 12q18-5 33 0m21-12q18-5 33 0m-33 12q18-5 33 0M85 239h250" /><circle cx="210" cy="120" r="14" /><path d="m210 102 0 36m-18-18h36M96 153H77m246 0h20" /></> : id === 'buddhism' ? <><circle cx="210" cy="138" r="82" /><circle cx="210" cy="138" r="65" /><circle cx="210" cy="138" r="19" />{Array.from({ length: 8 }, (_, i) => <g key={i} transform={`rotate(${i * 45} 210 138)`}><path d="M210 119V56m-7 20 7-7 7 7" /><circle cx="210" cy="56" r="4" /></g>)}<path d="M127 241q83 16 166 0M152 258h116" /></> : id === 'hinduism' ? <><path d="M210 222q-54-32 0-137 54 105 0 137ZM210 222q-89-9-93-91 75 19 93 91ZM210 222q89-9 93-91-75 19-93 91ZM210 222q-104 35-127-25 65-25 127 25ZM210 222q104 35 127-25-65-25-127 25Z" /><circle cx="210" cy="105" r="64" strokeDasharray="3 8" /><path d="M210 28v24M92 248h236M149 266h122" /></> : <><circle cx="210" cy="138" r="80" /><ellipse cx="210" cy="138" rx="34" ry="80" /><path d="M130 138h160m-148-40h136m-136 80h136M95 228h230" /><path d="m210 32 5 12-5 12-5-12ZM90 125h24m192 0h24" /><circle cx="210" cy="138" r="7" /></>}
  </svg>;
}
function identity(id: string) { return identities[id] ?? { accent: 'var(--epistles)', theme: 'Texts · questions · conversation', name: id }; }
export function WorldviewIndex() {
  return <div className="wv-page"><ApBack /><header className="wv-index-head"><div><p className="ap-eyebrow">Across beliefs / Four starting points</p><h1>Understand deeply.<br /><em>Witness clearly.</em></h1></div><p>Start with a person, not a label.<br />Explore the questions that matter, with each tradition’s own texts open beside Scripture.</p></header><div className="wv-collections">{WORLDVIEWS.map((item, index) => <Link className="wv-collection" key={item.id} to={base + '/worldviews/' + item.id} style={{ '--wv-accent': identity(item.id).accent } as React.CSSProperties}><div className="wv-collection-meta"><span>0{index + 1} / A conversation in context</span><ArrowUpRight size={20} /></div><CollectionArt id={item.id} /><div className="wv-collection-copy"><p className="ap-eyebrow">{identity(item.id).theme}</p><h2>{item.title}</h2><p>{item.description}</p><div className="wv-collection-foot"><span>{item.rows.length} questions · {item.studies.length} connected studies</span><strong>Enter the collection <ArrowRight size={16} /></strong></div></div></Link>)}</div><div className="wv-method"><span>Before the comparison</span><p>These are focused introductions. Ask which texts, teachers and interpretations your neighbour trusts. Read in context. Let the person tell you what they believe.</p><Link to={base + '/sources'}>How we use sources <ArrowUpRight size={14} /></Link></div></div>;
}
export function WorldviewPage({ book }: { book: ApNotebook }) {
  const { id = '' } = useParams();
  const item = WORLDVIEWS.find((worldview) => worldview.id === id);
  if (!item) return <div className="ap-empty"><h1>Collection not found.</h1><Link to={base + '/worldviews'}>Explore worldviews</Link></div>;
  return <Collection key={id} item={item} book={book} />;
}
function Collection({ item, book }: { item: typeof WORLDVIEWS[number]; book: ApNotebook }) {
  const [params, setParams] = useSearchParams();
  const [notes, setNotes] = useState(false);
  const selected = Math.max(0, item.rows.findIndex((row) => row.study === params.get('question')));
  const row = item.rows[selected], theme = identity(item.id);
  const choose = (index: number) => { const next = new URLSearchParams(params); next.set('question', item.rows[index].study); setParams(next, { replace: true, preventScrollReset: true }); };
  return <div className="wv-page" style={{ '--wv-accent': theme.accent } as React.CSSProperties}><ApBack to={base + '/worldviews'}>All worldviews</ApBack><header className="wv-hero"><div><p className="ap-eyebrow">Across beliefs / {theme.theme}</p><h1>{item.title.split(' & ')[0]}<br /><em> & {item.title.split(' & ')[1] ?? theme.name}</em></h1><p>{item.description}</p><a className="wv-start" href="#comparison">Begin with a question <ArrowRight size={17} /></a></div><div className="wv-hero-art"><CollectionArt id={item.id} /><span>Open texts. Honest questions.</span></div></header><div className="wv-reading-bar"><span><strong>01</strong> Examine the claims</span><span><strong>02</strong> Follow the sources</span><span><strong>03</strong> Carry the conversation</span></div>
    <section id="comparison" className="wv-desk"><div className="wv-section-title"><p className="ap-eyebrow">01 / Begin with the claims</p><h2>{item.subtitle}</h2><p>Choose a question. Read both starting points. Then follow the study.</p></div><div className="wv-desk-layout"><nav className="wv-question-nav" aria-label="Comparison questions">{item.rows.map((entry, i) => <button key={entry.question} type="button" aria-pressed={selected === i} aria-controls="wv-comparison-content" onClick={() => choose(i)}><span>0{i + 1}</span><strong>{entry.question}</strong><ArrowRight size={16} /></button>)}</nav><div id="wv-comparison-content" className="wv-comparison-content"><div className="wv-current-question"><span>Question 0{selected + 1} / 0{item.rows.length}</span><h3>{row.question}</h3></div><div className="wv-positions"><article><p className="ap-eyebrow"><BookOpen size={14} /> Christian starting point</p><p>{row.christian}</p><ApCitations citations={row.christianBasis} label="Scripture & Christian witness" /></article><article><p className="ap-eyebrow"><BookOpen size={14} />{item.otherLabel}</p><p>{row.other}</p><ApCitations citations={row.otherBasis} label="Primary record" /></article></div><Link className="wv-study-link" to={studyUrl(row.study)}><div><span>Examine the reasoning</span><strong>{studyById(row.study)!.title}</strong></div><ArrowUpRight size={23} /></Link></div></div></section>
    <section className="wv-sources"><div className="wv-section-title"><p className="ap-eyebrow">02 / Read in context</p><h2>The texts behind<br /><em>the conversation.</em></h2><p>Open the passage, read what surrounds it, and compare translations. These sources record a tradition’s claims; their role is stated on each entry.</p></div><div className="ap-source-grid">{item.sources.map((source) => <SourceLink key={source} id={source} />)}</div></section>
    <section className="wv-next"><ApSectionHeading eyebrow="03 / Carry the conversation" title="Make the comparison a study." /><div className="wv-study-list">{item.studies.map((id, i) => { const study = studyById(id)!; return <Link key={id} to={studyUrl(id)}><span>{book.notebook.read.includes(id) ? <Check size={18} /> : String(i + 1).padStart(2, '0')}</span><div><h3>{study.title}</h3><p>{study.summary}</p></div><small>{studyMinutes(study)} min</small><ArrowUpRight size={18} /></Link>; })}</div><div className="wv-conversation"><div><p className="ap-eyebrow">Listen before you answer</p><h3>What would you want to ask next?</h3><p>Start with the selected question: {row.question} Ask how your neighbour understands it before offering your answer.</p><button type="button" onClick={() => setNotes(!notes)} aria-expanded={notes}>{notes ? 'Close reflection' : 'Write a reflection'} <ArrowRight size={15} /></button></div>{item.id === 'islam' ? <Link className="wv-guided" to={base + '/paths/muslim-neighbour'}><RouteIcon size={24} /><span><strong>A route through the questions</strong>Follow the Muslim neighbour learning path.</span><ArrowRight size={18} /></Link> : <Link className="wv-guided" to={base + '/practice'}><RouteIcon size={24} /><span><strong>From study to conversation</strong>Practise listening and explaining your faith.</span><ArrowRight size={18} /></Link>}</div>{notes && <ApNote id={'worldview-' + item.id} prompt="Which claim or passage would you examine with your neighbour?" book={book} />}</section>
  </div>;
}
