import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, Bookmark, Check, Search } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { PassageText, RefLink } from "./study/StudyParts";
import { PATHS, TOPICS, sourceById, studyById, studyMinutes, topicById, type ApStudy } from "@/data/apologetics-library";
import type { ApNotebook } from "@/lib/apologetics-notebook";
import type { ApCitation } from "@/data/apologetics-types";
import { AP_BASE, studyUrl, apColor } from "@/lib/apologetics-links";

export function ApBack({ to = AP_BASE, children = "Back to Apologetics" }: { to?: string; children?: ReactNode }) { return <Link className="ap-back" to={to}><ArrowLeft size={14} />{children}</Link>; }
export function ApHeading({ eyebrow, title, lead, children }: { eyebrow: string; title: string; lead: string; children?: ReactNode }) { return <header className="ap-page-heading"><ApBack /><p className="ap-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="ap-lead">{lead}</p>{children}</header>; }
export function ApSectionHeading({ eyebrow, title, to, link }: { eyebrow: string; title: string; to?: string; link?: string }) { return <div className="ap-section-heading"><div><p className="ap-eyebrow">{eyebrow}</p><h2>{title}</h2></div>{to && <Link to={to}>{link} <ArrowRight size={15} /></Link>}</div>; }
export function TopicArt({ index }: { index: number }) {
  return <svg viewBox="0 0 220 130" fill="none" aria-hidden="true" className="ap-topic-art">
    {index === 0 && <><circle cx="110" cy="65" r="43" /><ellipse cx="110" cy="65" rx="73" ry="23" transform="rotate(-28 110 65)" /><ellipse cx="110" cy="65" rx="73" ry="23" transform="rotate(28 110 65)" /><circle cx="110" cy="65" r="7" fill="currentColor" /><path d="M110 7v16m0 84v16M22 65h19m138 0h19" /></>}
    {index === 1 && <><path d="M65 114V59a45 45 0 0 1 90 0v55M52 114V59a58 58 0 0 1 116 0v55M39 114h142M110 34v66M90 55h40" /><path d="m65 114-20 12m110-12 20 12" /><circle cx="110" cy="55" r="14" strokeDasharray="2 5" /></>}
    {index === 2 && <><path d="M35 26q38-17 75 2v80q-37-19-75-2ZM110 28q37-19 75-2v80q-38-17-75 2Z" /><path d="M47 41q24-8 50 2m-50 12q24-8 50 2m-50 12q24-8 50 2m-50 12q24-8 50 2m27-40q24-10 49-2m-49 16q24-10 49-2m-49 16q24-10 49-2" /><path d="m141 23 0 60 8-7 8 7V22" fill="currentColor" fillOpacity=".12" /></>}
    {index === 3 && <><path d="M25 86q25-40 51 0t51 0 51 0M25 101q25-40 51 0t51 0 51 0" /><circle cx="110" cy="40" r="17" /><path d="M110 10V1m-26 14-7-7m59 7 7-7M76 40H64m80 0h12m-77 24-8 8m70-8 8 8" /></>}
    {index === 4 && <><circle cx="110" cy="65" r="46" /><ellipse cx="110" cy="65" rx="22" ry="46" /><path d="M64 65h92M70 43h80M70 87h80M20 65h34m112 0h34" /><circle cx="18" cy="65" r="4" fill="currentColor" /><circle cx="202" cy="65" r="4" fill="currentColor" /></>}
    {index === 5 && <><path d="M30 25h105v50H70L48 96V75H30ZM147 46h43v51h-18v17l-22-17h-48V85" /><path d="M48 43h69M48 57h49" /><circle cx="146" cy="72" r="3" fill="currentColor" /><circle cx="159" cy="72" r="3" fill="currentColor" /><circle cx="172" cy="72" r="3" fill="currentColor" /></>}
  </svg>;
}
export function Constellation() {
  const points = [[50, 10], [81, 29], [81, 74], [50, 94], [19, 74], [19, 29]];
  return <nav className="ap-constellation" aria-label="Explore connected topics"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><ellipse cx="50" cy="52" rx="35" ry="40" /><ellipse cx="50" cy="52" rx="26" ry="30" />{points.map(([x, y], index) => <path key={index} d={`M50 52 Q${x} 52 ${x} ${y}`} />)}{Array.from({ length: 35 }, (_, i) => <circle key={i} cx={(i * 37 + 3) % 100} cy={(i * 19 + 7) % 100} r={i % 5 ? .14 : .35} />)}</svg><div className="ap-constellation-center"><span>✦</span><strong>Faith seeking<br />understanding.</strong><small>Follow a question</small></div>{TOPICS.map((topic, i) => <Link key={topic.id} to={AP_BASE + "/topics/" + topic.id} className="ap-orbit-node" style={{ ...apColor(topic.color), left: points[i][0] + "%", top: points[i][1] + "%" }}><i /><span>{topic.short}</span><ArrowUpRight size={12} /></Link>)}</nav>;
}
export function StudyCard({ study, book }: { study: ApStudy; book: ApNotebook }) {
  const topic = topicById(study.topic)!;
  return <article className="ap-study-card" style={apColor(topic.color)}><div className="ap-card-meta"><span>{topic.short} · {studyMinutes(study)} min</span><button type="button" aria-label={(book.notebook.saved.includes(study.id) ? "Unsave: " : "Save: ") + study.title} aria-pressed={book.notebook.saved.includes(study.id)} onClick={() => book.toggle("saved", study.id)}><Bookmark size={17} fill={book.notebook.saved.includes(study.id) ? "currentColor" : "none"} /></button></div><Link to={studyUrl(study.id)}><h3>{study.title}</h3><p>{study.summary}</p><span>{book.notebook.read.includes(study.id) ? <><Check size={14} />Read · Revisit study</> : <>Follow the question <ArrowRight size={15} /></>}</span></Link></article>;
}
export function SourceLink({ id }: { id: string }) { const source = sourceById(id); return <a href={source.url} target="_blank" rel="noreferrer" className="ap-source-link"><div><span>{source.kind}</span><strong>{source.title}</strong><small>{source.author}</small><small className="ap-source-role">{source.role}</small></div><ArrowUpRight size={16} /></a>; }
export function ApCitations({ citations, label = "Basis" }: { citations: ApCitation[]; label?: string }) {
  return <div className="ap-citations" aria-label={label}><span className="ap-citation-label">{label}</span><ul>{citations.map((citation, index) => <li key={index}>{citation.kind === "scripture" ? <RefLink span={citation.span} /> : <a href={sourceById(citation.source).url} target="_blank" rel="noreferrer" title={sourceById(citation.source).note}><span>{citation.source === "wcf" ? "Westminster" : sourceById(citation.source).author.split(" · ")[0]}</span><span className="ap-citation-locator">{citation.locator}</span><ArrowUpRight size={11} /></a>}</li>)}</ul></div>;
}
export function ApSourcePolicy({ compact = false }: { compact?: boolean }) {
  return <section className={"ap-source-policy" + (compact ? " is-compact" : "")} aria-label="Our doctrinal basis"><p className="ap-eyebrow">Scripture first · Reformed convictions</p><h2>Know what stands behind the answer.</h2><p>We receive Scripture as our final authority. These guides use the Westminster Confession as a subordinate doctrinal standard, with exposition from Reformed theologians. Read the passage and the cited section together.</p>{!compact && <><ApCitations citations={[{ kind: "scripture", span: [55003016, 55003017] }, { kind: "source", source: "wcf", locator: "1.4–10" }]} /><div className="ap-policy-grid"><div><h3>Teaching and explanation</h3><p>Reformed confessions and theologians explain the doctrines taught here. Our paragraphs are original study notes, not quotations or a claim that the named authors reviewed this site.</p></div><div><h3>Limited agreement</h3><p>Aquinas is used for causation and dependence. Augustine contributes on grace; Athanasius supplies a historical New Testament list. Each use has a stated scope. None endorses every doctrine of its author or erases disagreements over justification, merit, canon or church authority.</p></div><div><h3>Records of other positions</h3><p>The Qur’an, a humanist declaration and debate transcripts document claims to examine. They are not doctrinal authorities here. Craig's participation in a debate does not make him a Reformed teacher for this library.</p></div></div></>}{compact && <Link to={AP_BASE + "/sources"}>Our sources and their scope <ArrowRight size={14} /></Link>}</section>;
}
export function ApNote({ id, prompt, book }: { id: string; prompt: string; book: ApNotebook }) { return <div className="ap-note"><label htmlFor={"ap-note-" + id}><span className="ap-eyebrow">Your reflection</span>{prompt}</label><textarea id={"ap-note-" + id} rows={4} maxLength={8000} value={book.notebook.notes[id] ?? ""} onChange={(event) => book.note(id, event.target.value)} placeholder="Put the question, insight or next step into your own words…" /><small>{book.storageError ? "Not saved — browser storage is unavailable." : "Saved on this device as you write. Notes stay in this browser; clearing its data removes them."}</small></div>; }
export function ApPassages({ study }: { study: ApStudy }) { const [open, setOpen] = useState(false); return <div className="ap-passages"><p className="ap-eyebrow"><BookOpen size={14} />Open the Scriptures</p>{study.refs.map((ref, index) => <div key={index}><RefLink span={ref.span} /><p>{ref.note}</p></div>)}<button className="ap-text-button" type="button" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? "Close passage preview" : "Read the first passage here"}</button>{open && <div className="ap-passage-preview"><PassageText span={study.refs[0].span} max={8} /></div>}</div>; }
export function PathCard({ path, index, book }: { path: typeof PATHS[number]; index: number; book: ApNotebook }) {
  const read = path.studies.filter((id) => book.notebook.read.includes(id)).length;
  return <Link to={AP_BASE + "/paths/" + path.id} className="ap-path-card"><span className="ap-path-number">0{index + 1}</span><p className="ap-eyebrow">{path.label}</p><h3>{path.title}</h3><p>{path.description}</p><div className="ap-path-dots" aria-hidden="true">{path.studies.map((id) => <i key={id} className={book.notebook.read.includes(id) ? "is-read" : ""} />)}</div><span>{read ? read + "/" + path.studies.length + " read" : path.studies.length + " connected studies"} · {path.studies.reduce((n, id) => n + studyMinutes(studyById(id)!), 0)} min <ArrowRight size={15} /></span></Link>;
}
export function ApSearch({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="ap-search"><Search size={18} /><span className="sr-only">Search studies</span><input type="search" placeholder="Search questions, ideas or objections…" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
