import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const website=path.resolve(dir,'../..');
const preview=path.join(dir,'preview.tsx');
fs.writeFileSync(preview,fs.readFileSync(preview,'utf8').replace("className={path==='worldviews'?'active':''}","aria-current={path==='worldviews'?'page':undefined}"));
const catalogPath=path.join(website,'design/catalog.json');
const catalog=JSON.parse(fs.readFileSync(catalogPath,'utf8'));
let section=catalog.sections.find(x=>x.id==='apologetics');
if(!section){section={id:'apologetics',title:'Apologetics',line:'Local design previews for the Apologetics library.',page:'/apologetics',cards:[]};catalog.sections.push(section)}
const card={id:'christianity-islam',title:'Christianity & Islam · Expanded library',url:'/mockups/christianity-islam/',date:'2026-10-09',status:'option',line:'The current site header, typography, artwork, twelve-question desk, four reading stages and working atlas, with proposed Understanding Islam and Ministry pages around them.'};
const existing=section.cards.findIndex(x=>x.id===card.id);
if(existing>=0)section.cards[existing]=card;else section.cards.push(card);
fs.writeFileSync(catalogPath,JSON.stringify(catalog,null,2)+'\n');
const strategy=path.resolve(website,'../Research/Apologetics/Islam/2026-10-09/strategy');
const old=path.join(strategy,'design-preview.html');
const preserved=path.join(strategy,'design-preview-v1.html');
if(!fs.existsSync(preserved))fs.copyFileSync(old,preserved);
const redirect='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Christianity and Islam · Revised local mockup</title><meta http-equiv="refresh" content="0;url=http://127.0.0.1:8931/mockups/christianity-islam/"></head><body><p><a href="http://127.0.0.1:8931/mockups/christianity-islam/">Open the revised local mockup</a></p></body></html>\n';
fs.writeFileSync(old,redirect);
fs.writeFileSync('D:/FortressOfSolitude/Sites/christianity-islam-design/dist/index.html',redirect);
const readme=path.join(strategy,'README.md');
let text=fs.readFileSync(readme,'utf8');
const note='> **Mockup revision:** The current interactive preview is [on the existing local server](http://127.0.0.1:8931/mockups/christianity-islam/). It reuses current site components and includes nine views. The earlier five-view standalone prototype is preserved in `design-preview-v1.html`; its verification files apply only to that earlier version. Current mockup source, implementation notes and verification are in `Website/design/christianity-islam/`. The architecture and research plan remain proposals.\n\n';
if(!text.includes('> **Mockup revision:**'))text=text.replace('Status: **ready for owner review;',note+'Status: **ready for owner review;');
text=text.replace('[Interactive design concept with five views](design-preview.html)','[Revised interactive concept on localhost](http://127.0.0.1:8931/mockups/christianity-islam/)');
fs.writeFileSync(readme,text);
console.log('Local pointers and gallery registration updated. No hosted publication.');
