#!/usr/bin/env python3
"""Readable addresses for people's pages (owner, 2026-10-08): /people/peter, /people/james-son-of-zebedee, in place of
/people/james-mat-4-21 (STEP Bible's id: the name plus the first verse that names him).

The rule: the plain name when no other person in the site's people data bears it; when the name is shared, the name
plus Scripture's own label for him ("son of Zebedee", "the Zealot", "Iscariot"). This first release covers the Twelve,
Matthias and Paul. The script stops if a plain name is not unique, if two people would share an address, or if an
address would collide with an existing person id. The old addresses keep working: the site forwards them.

    py -3.12 scripts/build-people-slugs.py           # write src/data/people-slugs.json
    py -3.12 scripts/build-people-slugs.py --check   # fail if the file is out of date
"""
import json
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
SITE = Path(__file__).resolve().parent.parent
PEOPLE = SITE / "data" / "study" / "people.json"
OUT = SITE / "src" / "data" / "people-slugs.json"

# person id -> (the name used, and whether it is the plain name, which must be unique among all people)
APOSTLES: dict[str, tuple[str, bool]] = {
    "peter-mat-4-18": ("Peter", True),
    "andrew-mat-4-18": ("Andrew", True),
    "james-mat-4-21": ("James son of Zebedee", False),
    "john-mat-4-21": ("John son of Zebedee", False),
    "philip-mat-10-3": ("Philip the apostle", False),  # Acts also has Philip the evangelist (Acts 21:8)
    "bartholomew-mat-10-3": ("Bartholomew", True),
    "thomas-mat-10-3": ("Thomas", True),
    "matthew-mat-9-9": ("Matthew", True),
    "james-mat-10-3": ("James son of Alphaeus", False),
    "judas-mat-10-3": ("Thaddaeus", True),  # the people data names him Judas (of James); no person is named Thaddaeus
    "simon-mat-10-4": ("Simon the Zealot", False),
    "judas-mat-10-4": ("Judas Iscariot", False),
    "matthias-act-1-23": ("Matthias", True),
    "paul-act-7-58": ("Paul", True),
}


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def build() -> dict:
    if not PEOPLE.exists():
        raise SystemExit(f"people data not found at {PEOPLE}: run the data build first")
    people = [p for p in json.loads(PEOPLE.read_text(encoding="utf-8")) if not p.get("g")]
    ids = {p["id"] for p in people}
    names: dict[str, int] = {}
    for p in people:
        names[p["n"]] = names.get(p["n"], 0) + 1
    slugs: dict[str, str] = {}
    errors: list[str] = []
    for person_id, (name, plain) in APOSTLES.items():
        if person_id not in ids:
            errors.append(f"{person_id}: not a person in {PEOPLE.name}")
        if plain and names.get(name, 0) > 1:
            errors.append(f"{person_id}: the plain name {name!r} is shared by {names[name]} people; give Scripture's label")
        slug = slugify(name)
        if slug in slugs:
            errors.append(f"{person_id}: address /people/{slug} already belongs to {slugs[slug]}")
        if slug in ids:
            errors.append(f"{person_id}: address /people/{slug} would collide with the person id {slug!r}")
        slugs[slug] = person_id
    if errors:
        raise SystemExit("people slugs: " + "; ".join(errors))
    return {"about": "Readable people addresses: slug -> person id. Generated by scripts/build-people-slugs.py; do not edit.", "slugs": slugs}


def main() -> int:
    data = build()
    text = json.dumps(data, ensure_ascii=False, indent=1) + "\n"
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(SITE)} is out of date: run py -3.12 scripts/build-people-slugs.py")
            return 1
        print(f"{OUT.relative_to(SITE)} is up to date ({len(data['slugs'])} addresses)")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(SITE)}: {len(data['slugs'])} addresses")
    return 0


if __name__ == "__main__":
    sys.exit(main())
