#!/usr/bin/env python3
"""Build src/data/who-ruled/<BOOK>.json: "Who ruled when" for the reader, one small file per book of the 66, loaded only
when that book is read (src/lib/who-ruled.ts, src/components/reader/WhoRuled.tsx). Only verse evidence, never dates.
For each chapter it lists the rulers the text itself ties to it, each with its reason:

  dated    Scripture's own dating statement covers the chapter (content/people/chapter-dating.json "dated")
  title    a psalm title ties the psalm to a king's reign ("titles", keyed by chapter: titles have no verse number)
  named    a ruler with a page whose person records (data/study/people/<id>.json "refs", records joined by "same"
           counted as one person) name them in this chapter
  account  the chapter is inside one of the ruler page's own passages of more than one verse, in a narrative book
           (Genesis-Esther, Matthew-Acts); shown as "during his reign" only when the chapter neither names nor dates them

plus the prophets (data/study/prophets.json) named in the chapter, and dating statements that name no ruler (Ezekiel's
"sixth year"), which are kept for the chapter without one. The book's heading, "none" and "related" entries are copied
per book; the reader shows the heading on every chapter. Rulers who are also prophets (Moses, Samuel, Deborah) are
listed once, as rulers.

    py -3.12 scripts/build-reader-rulers.py          # writes the files (the site build runs it after the index)
    py -3.12 scripts/build-reader-rulers.py --check  # exit 1 if any file is out of date

It reads src/data/people-pages/index.json (run scripts/build-people-pages-index.py first), the ruler group files beside
it, and data/study (generated by scripts/build-study.py, git-ignored). The output is committed, so when data/study is
missing the files are left as they are.
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
SITE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SITE / "scripts"))
from bible.books import BOOKS

PAGES = SITE / "src" / "data" / "people-pages"
INDEX = PAGES / "index.json"
STUDY = SITE / "data" / "study"
PEOPLE = STUDY / "people"
DATING = SITE / "content" / "people" / "chapter-dating.json"
OUT = SITE / "src" / "data" / "who-ruled"
CODES = [b[0] for b in BOOKS[:66]]
# Books that tell events in order, where a chapter inside a reign's passages is "during" that reign. Never the poetry
# or the prophets (Isaiah 36–39 is narrative, but those chapters name their king anyway).
NARRATIVE = set(range(1, 18)) | set(range(40, 45))


def chapter_key(verse_id: int) -> int:
    """book * 1000 + chapter, as chapter-dating.json's `covers`."""
    return verse_id // 1000


def book_num(value) -> int | None:
    if isinstance(value, int):
        return value if 1 <= value <= 66 else None
    if isinstance(value, str) and value.upper() in CODES:
        return CODES.index(value.upper()) + 1
    return None


def load_json(path: Path, problems: list[str]):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        problems.append(f"{path.relative_to(SITE)}: could not be read ({error})")
        return None


class People:
    """Person records (refs and names) and the ruler page each person id belongs to."""

    def __init__(self, index: dict, problems: list[str]):
        self.problems = problems
        self.rulers = {r["id"]: r for r in index["rulers"]}
        self.names = {row["id"]: row["n"] for row in json.loads((STUDY / "people.json").read_text(encoding="utf-8"))}
        self._refs: dict[str, list[int]] = {}
        same: dict[str, str] = {}
        for file in PEOPLE.glob("*.json"):
            record = json.loads(file.read_text(encoding="utf-8"))
            self._refs[file.stem] = record.get("refs", [])
            if isinstance(record.get("same"), str):
                same[file.stem] = record["same"]
        # Records that are one person ("same": shallum-1ch-3-15 -> jehoahaz-2ki-23-30) count as one, refs and all.
        self.canonical: dict[str, str] = {}
        for pid in self._refs:
            seen, at = {pid}, pid
            while at in same and same[at] not in seen:
                at = same[at]
                seen.add(at)
            self.canonical[pid] = at
        self.members: dict[str, set[str]] = {}
        for pid, root in self.canonical.items():
            self.members.setdefault(root, set()).add(pid)
        # Prophet pages ("the word", /people/<id>/word), when the index has them.
        self.word_of: dict[str, str] = {}
        for prophet in index.get("prophets") or []:
            for pid in [prophet["id"], *(prophet.get("personIds") or [])]:
                for member in self.group(pid):
                    self.word_of.setdefault(member, prophet["id"])
        self.page_of: dict[str, str] = {}
        for r in index["rulers"]:
            for pid in [r["id"], *(r.get("personIds") or [])]:
                for member in self.group(pid):
                    self.page_of.setdefault(member, r["id"])

    def group(self, person_id: str) -> set[str]:
        """Every record of the same person (itself, and any joined to it by "same")."""
        return self.members.get(self.canonical.get(person_id, person_id), {person_id}) | {person_id}

    def refs(self, person_id: str) -> list[int]:
        return sorted({v for member in self.group(person_id) for v in self._refs.get(member, [])})

    def page_refs(self, ruler_id: str) -> list[int]:
        ruler = self.rulers[ruler_id]
        return sorted({v for pid in [ruler_id, *(ruler.get("personIds") or [])] for v in self.refs(pid)})

    def resolve(self, any_id: str, where: str) -> str | None:
        """A ruler-page id or person id from chapter-dating.json -> the ruler page id, or the person id when there is no
        page. Unknown ids are reported and dropped."""
        if any_id in self.page_of:
            return self.page_of[any_id]
        if any_id in self.names:
            return self.canonical.get(any_id, any_id)
        self.problems.append(f"chapter-dating.json {where}: unknown person id {any_id!r}; left out")
        return None


def load_passages(problems: list[str]) -> dict[str, list[list[int]]]:
    out: dict[str, list[list[int]]] = {}
    for file in sorted(PAGES.glob("*.json")):
        if file == INDEX:
            continue
        data = load_json(file, problems)
        for ruler in (data or {}).get("rulers") or []:
            out.setdefault(ruler["id"], ruler.get("passages") or [])
    return out


def load_dating(people: People, problems: list[str]) -> dict:
    empty = {"headings": [], "none": [], "dated": [], "related": [], "titles": []}
    if not DATING.exists():
        return empty
    data = load_json(DATING, problems)
    if not isinstance(data, dict):
        return empty
    out = {key: [e for e in data.get(key) or [] if isinstance(e, dict)] for key in empty}
    for key, entries in out.items():
        for n, entry in enumerate(entries):
            where = f"{key}[{n}]"
            entry["rulers"] = [r for r in (people.resolve(i, where) for i in entry.get("rulers") or []) if r]
            if entry.get("prophet"):
                entry["prophet"] = people.resolve(entry["prophet"], where)
            if key in ("headings", "none", "related") and book_num(entry.get("book")) is None:
                problems.append(f"chapter-dating.json {where}: unknown book {entry.get('book')!r}; left out")
                entry["skip"] = True
            if key == "titles" and not (isinstance(entry.get("chapter"), int) and book_num(entry["chapter"] // 1000)):
                problems.append(f"chapter-dating.json {where}: chapter must be book * 1000 + chapter; left out")
                entry["skip"] = True
            if key in ("headings", "dated", "related") and not valid_span(entry.get("span")):
                problems.append(f"chapter-dating.json {where}: span must be [first verse id, last verse id]; left out")
                entry["skip"] = True
            if key == "dated" and not (isinstance(entry.get("covers"), list) and len(entry["covers"]) == 2):
                problems.append(f"chapter-dating.json {where}: covers must be [first chapter, last chapter]; left out")
                entry["skip"] = True
        out[key] = [e for e in entries if not e.get("skip")]
    return out


def valid_span(span) -> bool:
    return isinstance(span, list) and len(span) == 2 and all(isinstance(v, int) and v > 1_000_000 for v in span)


def span_chapters(span: list[int]) -> range:
    return range(chapter_key(span[0]), chapter_key(span[1]) + 1)


def ruler_card(ruler: dict) -> dict:
    """What the reader shows of a ruler without loading the people-page index."""
    out = {key: ruler[key] for key in ("name", "title", "kind", "realm", "sex") if key in ruler}
    if ruler.get("dates"):
        out["dates"] = ruler["dates"]
    if ruler.get("prophets"):
        out["prophets"] = len(ruler["prophets"])
    return out


def rank(item: dict) -> tuple:
    """Dated first, then named (the chapter's own subject, inside their account, before a passing mention; then the most
    verses), then "during" the reign."""
    named = sorted(set(item.get("named") or []))
    if item.get("dated") or item.get("title"):
        return (0, 0, 0)  # in the order the dating verse names them (the sort keeps it)
    if named:
        tier = 1 if item.get("account") else 2
    else:
        tier = 3
    return (tier, -len(named), named[0] if named else 0)


def build_book(num: int, people: People, passages: dict, prophets: list[str], dating: dict) -> dict:
    code = CODES[num - 1]
    chapters: dict[int, dict] = {}

    def chapter(ch: int) -> dict:
        return chapters.setdefault(ch, {"rulers": {}, "prophets": {}, "statements": []})

    def ruler_item(ch: int, ruler_id: str) -> dict:
        return chapter(ch)["rulers"].setdefault(ruler_id, {"id": ruler_id})

    # Scripture's dating statements, then the psalm titles (no verse number of their own). A statement that names no
    # ruler (Ezekiel's "sixth year", Nehemiah 1:1) is kept for the chapter on its own: never given a ruler.
    statements = [(e, range(e["covers"][0], e["covers"][1] + 1), "dated") for e in dating["dated"]]
    statements += [(e, range(e["chapter"], e["chapter"] + 1), "title") for e in dating["titles"]]
    for entry, keys, kind in statements:
        why = {k: entry[k] for k in ("span", "quote", "why", "note") if entry.get(k)}
        for key in keys:
            if key // 1000 != num:
                continue
            for rid in entry["rulers"]:
                ruler_item(key % 1000, rid).setdefault(kind, []).append(why)
            if not entry["rulers"]:
                chapter(key % 1000)["statements"].append({**why, **({"title": True} if kind == "title" else {})})

    for rid in people.rulers:
        for verse in people.page_refs(rid):
            if verse // 1_000_000 == num:
                item = ruler_item(chapter_key(verse) % 1000, rid)
                item.setdefault("named", []).append(verse % 1000)
        if num in NARRATIVE:
            for span in passages.get(rid) or []:
                if span[0] // 1_000_000 != num or span[0] == span[1]:  # one verse is a mention, not an account of the reign
                    continue
                for key in span_chapters(span):
                    if key // 1000 == num:
                        ruler_item(key % 1000, rid).setdefault("account", span)

    for pid in dict.fromkeys(people.canonical.get(p, p) for p in prophets):
        if any(member in people.page_of for member in people.group(pid)):
            continue  # a ruler as well (Moses, Samuel, Deborah): listed among the rulers
        for verse in people.refs(pid):
            if verse // 1_000_000 == num:
                item = chapter(chapter_key(verse) % 1000)["prophets"].setdefault(pid, {"id": pid})
                item.setdefault("named", []).append(verse % 1000)

    out_chapters = {}
    for ch in sorted(chapters):
        entry = chapters[ch]
        rulers = []
        for item in sorted(entry["rulers"].values(), key=rank):
            if item.get("named"):
                item["named"] = sorted(set(item["named"]))
            rulers.append(item)
        prophets_here = sorted(entry["prophets"].values(), key=lambda p: p["named"][0])
        for p in prophets_here:
            p["named"] = sorted(set(p["named"]))
        shown = {}
        if rulers:
            shown["rulers"] = rulers
        if prophets_here:
            shown["prophets"] = prophets_here
        if entry["statements"]:
            shown["statements"] = entry["statements"]
        if shown:
            out_chapters[str(ch)] = shown

    book: dict = {"book": code}
    headings = [{k: e[k] for k in ("span", "quote", "rulers", "prophet", "note") if e.get(k)} for e in dating["headings"] if book_num(e["book"]) == num]
    none = [{k: e[k] for k in ("prophet", "note") if e.get(k)} for e in dating["none"] if book_num(e["book"]) == num]
    related = [{k: e[k] for k in ("span", "quote", "rulers", "note") if e.get(k)} for e in dating["related"] if book_num(e["book"]) == num]
    if headings:
        book["headings"] = headings
    if none:
        book["none"] = none
    if related:
        book["related"] = related
    book["chapters"] = out_chapters

    used = {i["id"] for c in out_chapters.values() for i in c.get("rulers", [])}
    used |= {r for e in headings + related for r in e.get("rulers", [])}
    prophets_used = {p["id"] for c in out_chapters.values() for p in c.get("prophets", [])}
    prophets_used |= {e["prophet"] for e in headings + none if e.get("prophet")}
    book["rulers"] = {rid: ruler_card(people.rulers[rid]) for rid in sorted(used) if rid in people.rulers}
    others = sorted((used - set(people.rulers)) | {p for p in prophets_used if p not in people.rulers})
    book["people"] = {pid: people.names.get(pid, pid) for pid in others}
    words = {pid: people.word_of[pid] for pid in others if pid in people.word_of}
    if words:
        book["words"] = words
    return book


def main() -> int:
    problems: list[str] = []
    check = "--check" in sys.argv
    if not PEOPLE.is_dir() or not (STUDY / "prophets.json").exists():
        print(f"warning: {PEOPLE.relative_to(SITE)} is missing (run scripts/build-study.py); {OUT.relative_to(SITE)} left as it is")
        return 0
    index = load_json(INDEX, problems)
    if not index:
        for problem in problems:
            print(f"warning: {problem}")
        return 1
    people = People(index, problems)
    passages = load_passages(problems)
    prophets = [p["id"] for p in json.loads((STUDY / "prophets.json").read_text(encoding="utf-8"))]
    dating = load_dating(people, problems)
    files = {f"{CODES[n - 1]}.json": json.dumps(build_book(n, people, passages, prophets, dating), ensure_ascii=False, separators=(",", ":")) + "\n" for n in range(1, 67)}
    for problem in problems:
        print(f"warning: {problem}")
    if check:
        stale = [name for name, text in files.items() if not (OUT / name).exists() or (OUT / name).read_text(encoding="utf-8") != text]
        extra = sorted(f.name for f in OUT.glob("*.json") if f.name not in files) if OUT.is_dir() else []
        if stale or extra or problems:
            if stale or extra:
                print(f"{OUT.relative_to(SITE)} is out of date ({', '.join(stale + extra)}); run scripts/build-reader-rulers.py")
            return 1
        print(f"{OUT.relative_to(SITE)} is up to date ({'with' if DATING.exists() else 'without'} chapter-dating.json)")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    changed = 0
    for name, text in files.items():
        target = OUT / name
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            target.write_text(text, encoding="utf-8", newline="\n")
            changed += 1
    chapters = sum(len(json.loads(t)["chapters"]) for t in files.values())
    print(f"Wrote {OUT.relative_to(SITE)}: 66 books, {chapters} chapters with rulers or prophets, {changed} files changed"
          f" ({'with' if DATING.exists() else 'without'} chapter-dating.json)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
