"""RB12 source-first historical documentation; final report is a separate last step."""
import hashlib,json,re
from datetime import datetime,timezone
from pathlib import Path
SITE=Path(__file__).resolve().parents[1];R=SITE/'content/library/reports/reformed-baptist-overnight/RB12';CACHE=SITE/'.local/library/run-rb12-2026-10-07'
def read(n):return json.loads((R/n).read_text('utf-8'))
def write(n,d):(R/n).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
def md(n,s):(R/n).write_text(s.strip()+'\n',encoding='utf-8',newline='\n')
def sha(b):return hashlib.sha256(b).hexdigest()
def main():
    works=read('chapter-map.json')['works'];new=read('acquisition-manifest.json')['files'];by={w['assetId']:w for w in works};rels=[]
    def witness(slug):return next(w for w in works if (w.get('workId') or '').endswith(slug))
    def location(w,title):return next(u for u in w['locations'] if u['title']==title)
    def relation(subject,predicate,obj,w,title,date,qualification):
        u=location(w,title);rels.append(dict(subject=subject,predicate=predicate,object=obj,date=date,qualification=qualification,assetId=w['assetId'],originalSha256=w['originalSha256'],sourceLocator=u['locator'],sourceUnitTitle=u['title'],graphAsserted=False,historicalEvidenceNotTheologicalEndorsement=True))
    w=witness('broadmead-1974');title='Hayden on editions, Underhill insertions and lost correspondence'
    relation('Edward Terrill','recorded; subsequently continued by unidentified members','Broadmead records',w,title,'1640-1687 record period; Terrill 1634-1685','Hayden identifies multiple hands; early retrospective narrative is not automatically a contemporary minute for every event.')
    relation('Edward Bean Underhill','modernized and inserted notes/correspondence into','Broadmead records',w,title,'1847 edition','Chronological insertion can alter manuscript sequence; some correspondence is known only through this edition.')
    relation('Roger Hayden','edited and compared earlier witnesses of','Broadmead records',w,title,'1974 edition','Historical editorial companion; copyright retained and no global doctrinal approval.')
    w=witness('kiffin-autobiography')
    relation('William Kiffin','authored a retrospective account of','his life and public conduct',w,'Kiffin: Public conduct and concluding address','seventeenth-century memoir, published 1823','Self-report with Orme notes and Gross modernization; chapter arrangement and modern page numbers belong to the edition.')
    relation('William Orme','introduced and annotated','Kiffin memoir',w,'Orme introduction','1823','Distinguish Orme narration from Kiffin and from letters quoted by either.')
    w=witness('knollys-life')
    relation('Hanserd Knollys','authored own account through','1672',w,'Knollys own life account to 1672','1692 publication','Later author manuscript explicitly lost; 18 marked illegibilities remain in the complete offered transcription.')
    relation('William Kiffin','contributed epistle and general continuation to','Knollys life',w,'Kiffin epistle to the reader','1692','Continuation and editor voice are distinct from autobiographical first-person testimony.')
    relation('Hanserd Knollys','addressed last legacy to','his congregation',w,'Knollys last legacy to the church','shortly before death in 1691','Pastoral letter not a comprehensive institutional constitution; precise composition date not supplied.')
    w=next(w for w in works if (w.get('logicalWorkKey')=='philadelphia-minutes-selected-1851') and any(u['title']=='Philadelphia association record 1707' for u in w['locations']))
    relation('Philadelphia Baptist Association','is described as organizing interchurch consultation among','Pennsylvania/Jersey congregations',w,'Philadelphia association record 1707','1707 as later collected','1851 edition summarizes earlier church records; modern claims of continuous institutional identity need separate evidence.')
    w=next(w for w in works if any(u['title']=='Philadelphia association record 1749' for u in w['locations']))
    relation('Philadelphia association','set out associational doctrine and order in','1749 record',w,'Philadelphia association record 1749','1749','Study its own language on delegated counsel and church relations; resemblance to confession chapter 26 is not proof of textual dependence.')
    for year,author,title,chapter in [('1785','William Rogers','Philadelphia 1785 circular: Justification / confession chapter XI','XI'),('1786','Thomas Ustick','Philadelphia 1786 circular: Adoption / confession chapter XII','XII')]:
        w=next(w for w in works if any(u['title']==title for u in w['locations']))
        relation(author,'expounded confession chapter '+chapter+' in','Philadelphia circular',w,title,year,'Signed association witness; 1786 web title is supplied, not original. Historical teaching remains attributed and scoped.')
    w=witness('belyea-origins')
    relation('Gordon L. Belyea','argued Puritan/separatist origins and distinguished','General and Particular Baptist movements',w,'Belyea: The JLJ Church, Southwark','May 2007','1633 rebaptism meaning and Kiffin Manuscript attribution remain qualified; no ancient uninterrupted succession graph asserted.')
    write('relationship-table.json',dict(mission='RB12',relationships=rels,graphAsserted=False))
    table=['# RB12 relationships before graphs','','These are source-qualified relationships for study. They are not verified graph assertions, inferred family trees, or universal theological endorsements.','','| Subject | Relationship | Object | Date / period | Source locator | Qualification |','|---|---|---|---|---|---|']
    for x in rels:table.append('| '+' | '.join(str(x[k]).replace('|','/') for k in ['subject','predicate','object','date'])+' | '+x['assetId']+' / '+x['sourceLocator']+' | '+x['qualification']+' |')
    md('RELATIONSHIPS.md','\n'.join(table))
    conf=by['asset-expanded-986603d125b04ec6fc5b'];anchors=[]
    for label,chapter,marker in [('Scripture authority',1,'authority of the Holy Scripture'),('Trinity',2,'three subsistences'),('Christ deity and humanity',8,'very and eternal God'),('Substitutionary atonement',8,'sacrifice of himself'),('Bodily resurrection',8,'arose from the dead'),('Grace through faith alone',11,'Faith thus receiving and resting')]:
        u=next(u for u in conf['locations'] if u['title'].startswith('CHAPTER '+str(chapter)+';'))
        anchors.append(dict(anchor=label,assetId=conf['assetId'],originalSha256=conf['originalSha256'],sourceLocator=u['locator'],lineStart=u['lineStart'],lineEnd=u['lineEnd'],literalMarker=marker,scope='Working confession reference, not automatic approval of every historian, contributor or historical claim.'))
    evidence=[]
    for p in (CACHE/'http').glob('*.json'):
        x=json.loads(p.read_text('utf-8'))
        if any(s in x['url'] for s in ['robots.txt','/metadata/','/contents.htm','phila.minutes.a.index','phila.minutes.a.title','phila.minutes.preface','Copyright.html','Classics.html','foundation-documents','A47565/master/README','A88025/master/README','publications/bristol-record-society-publications','/A47565/contents','/A88025/contents','Texts/master/TCP.csv']):evidence.append(x)
    write('theological-evidence.json',dict(mission='RB12',sixAnchors=anchors,primaryCachedEvidence=evidence,globalAuthorApproval=False,corpusLicenseEstablished=False,historicalSelection='Owner explicitly distinguishes primary historical evidence from theological endorsement. Confessional reference remains 1689; Hayden is historical editor only, Ivimey is dated historiography, cited opponents are not teaching acquisitions.',modernPublisherEvidence='TGC own foundation documents establish orthodox evangelical/Reformed publisher context; Belyea period bio and actual sourced argument establish scoped historical use. Not blanket approval of all journal articles.'))
    paths=[
      ('Where did Particular Baptists emerge?','Belyea: The JLJ Church, Southwark','Distinguish Independent beginnings, uncertain 1633 rebaptism and later explicit believer baptism; compare the held First London 1644/1646 witnesses.'),
      ('What can a local church record actually prove?','Broadmead account of the five-person 1640 gathering','Read Terrill as an edited retrospective record. Preserve mixed/open beginnings, later doctrinal development and unidentified continuators.'),
      ('How do editions change historical evidence?','Hayden on editions, Underhill insertions and lost correspondence','Compare 1847 modernization/insertions with the officially offered 1974 edition; one underlying record corpus, two witnesses.'),
      ('What did a persecuted Baptist say about his own life?','Kiffin: Religious changes','Compare self-report with Orme interpretation, the held Sober Discourse, and the primary London letter; never infer every political judgment is doctrine.'),
      ('What happened to Knollys\u2019s later autobiography?','Kiffin continuation / lost remainder notice','The edition states the remainder cannot be found. Treat continuation, legacy and publisher advertisements as different voices.'),
      ('How did churches cooperate without identical institutions?','Philadelphia association record 1707','Start with early associational practice and the 1749 doctrine/order essay; compare held Second London chapter 26 without asserting direct dependence.'),
      ('How were confessional doctrines taught by associations?','Philadelphia 1785 circular: Justification / confession chapter XI','William Rogers justification and Thomas Ustick adoption (1786) explicitly name confession chapters; retain supplied titles and signatures.'),
      ('How did war affect church cooperation?','Gillette note: no association meeting in 1777','No meeting is reported by a later editor. The repeated note is one editorial claim, not two contemporary meeting records.'),
      ('How did confessional Baptists move into organized missions?',None,'Reuse RB07 Fuller, Carey Enquiry, Serampore Agreement, letters, Judson and Rice; distinguish mission primary documents from later biography.'),
      ('Which origin stories need stronger corroboration?','Ivimey preface','Ivimey\u2019s ancient continuity program and Belyea\u2019s Puritan-roots argument are historiographical claims. Do not turn a narrative into genealogical or doctrinal certainty.')]
    entries=[];lines=['# RB12 historical reading map','','[Document table](DOCUMENT-TABLE.md) \u00b7 [Qualified relationships](RELATIONSHIPS.md) \u00b7 [Edition/coverage limits](COVERAGE.md) \u00b7 [Theological scope](THEOLOGICAL-SCOPE.md)','','| Historical question | Start here | What to preserve |','|---|---|---|']
    for q,title,note in paths:
        if title:
            w=next(w for w in works if any(u['title']==title for u in w['locations']));u=location(w,title);targets=[dict(assetId=w['assetId'],originalSha256=w['originalSha256'],locator=u['locator'],title=title)]
            link='['+title+']('+w['url']+') / '+u['locator']
        else:
            targets=[dict(assetId=w['assetId'],originalSha256=w['originalSha256'],locator=w['locations'][0]['locator'],title=w['title']) for w in works if w['status']=='already-held-RB07-reused'];link='[RB07 existing document map](../RB07/DOCUMENT-TABLE.md)'
        entries.append(dict(question=q,targets=targets,qualification=note));lines.append('| '+q+' | '+link+' | '+note+' |')
    write('reading-paths.json',dict(mission='RB12',paths=entries));md('READING-MAP.md','\n'.join(lines))
    dates=sorted({d['date'] for d in read('document-table.json')['documents'] if d.get('institution')=='Philadelphia Baptist Association' and d.get('documentKind') in ['association-record','association-minutes','association-circular'] and re.fullmatch(r'\d{4}',d.get('date') or '')})
    write('coverage.json',dict(mission='RB12',philadelphiaExplicitYearUnits=dates,fullCenturyHeld=False,missingYearNotAssumedMissingEvent=True,unacquiredStatisticalImages=read('selected-text-review.json'),newLogicalGroups=7,editionWitnesses=8,reusedWitnesses=51))
    md('COVERAGE.md',f'''# RB12 evidence coverage and limits

46 immutable originals / 5,243,750 bytes / 709,313 extracted words. Word totals include overlap, editorial matter, OCR noise and two Broadmead editions; they are not unique content totals. Seven logical work/collection groups, eight edition witnesses.

| Coverage | Actual holdings / useful slice | Limit |
|---|---|---|
| English historical narrative | Ivimey Volume I (1811), preface, ten chapters, notes and separately attributed prefixed Gill excerpt; thirteen HTML originals | Only offered Volume I. Volumes II-IV not collected. John Gill prefixed historical excerpt is acquired and separately authored, not his whole treatise; ancient ancestry claims are dated historiography. |
| Local congregation | Broadmead 1640-1687, Underhill 1847 and Hayden 1974 offered TXT | Two editions of the same records. Existing OCR errors, inserted correspondence, original spelling and different editorial methods remain distinct. |
| First-person witnesses | Kiffin 1823/2021, Knollys 1692/TCP, Kiffin joint letter 1659/60 | Kiffin lightly modernized; Knollys later manuscript lost. 18 and 1 TCP lacunae remain marked. Political/providential claims are attributed. |
| Philadelphia association | Twenty-seven offered pages: front matter, early church histories, four early-record parts, selected minutes and three circulars | Not the entire 1707-1807 book. Several statistics tables are image-only, intentionally not collected. 1785/1786/1801 are circulars, not whole annual minutes. |
| Explicit Philadelphia year units | {', '.join(dates)} | Years are actual mapped headings/dated pages. Lack of a heading does not prove no surviving record; 1777 is expressly a repeated later-editor no-meeting explanation. |
| Modern historical study | Belyea, Themelios 32.3, May 2007, pp. 40-67, complete essay and 75 rendered notes | Puritan-root argument remains the author's sourced thesis; cited historians are not acquired teaching sources. |
| Held doctrinal spine | 1644/1646 First London, Cox appendix, Second London digital witness, all 34 Philadelphia chapters, Kiffin communion treatise, Keach confession | Reused originals, not new acquisitions. Do not collapse edition dates, baptism/communion models, or Philadelphia's added laying-on-of-hands/singing chapters. |
| Missions / eighteenth-nineteenth century | All eleven previously mapped RB07 witnesses reused and re-hashed | No duplicate Fuller, Carey, Judson, Rice or Evans downloads. Primary documents remain separate from biography/editorial narration. |

The [document table](DOCUMENT-TABLE.md) has 194 rows across 97 witnesses / 490 exact reading locations; 27 private source slices are prepared for later review. The [relationship table](RELATIONSHIPS.md) has thirteen qualified rows and makes no graph assertions.
''')
    md('THEOLOGICAL-SCOPE.md','''# RB12 historical evidence and theological scope

The owner asks for historical evidence, with theological endorsement kept separate. Scripture and orthodox Reformed salvation doctrine remain the selection reference, with the Second London confession as the Baptist doctrinal anchor. Its actual held chapters 1, 2, 8 and 11 supply six verifiable doctrinal anchors in [theological-evidence.json](theological-evidence.json).

Primary records are evidence of what people wrote, reported or resolved. They do not endorse all political actions, disputed worship practices, providential interpretations, civic attitudes or historical conclusions. The campaign acquires no Catholic or progressive teaching work. Quoted opponents, publisher advertisements and references inside an eligible historical witness remain contextual material requiring segmentation, not additional approved authors.

- Ivimey is a Calvinistic Baptist historian writing in 1811, using primary quotations and a confessional continuity program. The early chapters do not establish an uninterrupted ancient Baptist succession. The web front matter adds an 1881 biography and contradicts itself about his death year (1830 heading, 1834 narrative). Preserve both, not an invented reconciliation.
- Broadmead started as a mixed/open-membership separatist gathering; later developments must remain dated. Terrill and unidentified continuators are distinct. Underhill's 1847 modernization and inserted notes/letters differ from Hayden's 1974 editorial witness. Hayden is admitted for historical/editorial evidence only; his affiliation or every doctrine is not globally approved.
- Kiffin's autobiography, Orme's 1823 introduction/notes, Gross's February 2021 modernization and embedded correspondence are different voices. Communion convictions should be studied with the already held Sober Discourse, not inferred from every memoir episode.
- Knollys's account ends where the surviving own-hand manuscript ends; the 1692 edition states the later remainder cannot be found. Kiffin's epistle/continuation and Knollys's last legacy are mapped separately. TCP long-s and marked gaps survive extraction; the modern bookplate and publisher advertisements are not approved teaching.
- Philadelphia's collected early records, contemporary minutes, doctrinal circulars, Gillette editorial notes, H. G. Jones preface, later web titles and statistical images require separate roles. The 1786 Adoption title is supplied; William Rogers and Thomas Ustick are the actual circular writers. Association decisions are not a universal Baptist polity mandate. No Landmark succession doctrine is approved from the repository name.
- Belyea's May 2007 essay is a source-supported evangelical Baptist historical argument. The source-period bio identifies a Baptist pastor and doctoral candidate; it does not establish his current office. TGC's actual foundation documents supply publisher context, not blanket approval of every article or cited author. Preserve uncertainty about 1633 rebaptism, manuscript attribution and Anabaptist influence.

All 46 parents and 27 prepared slices remain evidence-only and not ingested/embedded. CC0 applies expressly to the TCP keyboarded editions, not their page images. Other modern personal-reading offers do not establish corpus, FTS/vector or publication permission. Resolve rights and contributor roles at the post-RB14 aggregate gate.
''')
    md('INTAKE-NOTES.md','''# RB12 exact intake handoff

1. Reconcile seven logical work/collection groups and eight edition witnesses from [bibliography.json](bibliography.json). Forty-six physical files are not forty-six books; multipart Ivimey and Philadelphia offers are grouped deliberately, while Gill's separately authored prefixed excerpt retains its own work ID. These are provisional source-first identities, not additions to the formal author registry.
2. Verify immutable hashes and replay the 46 extractions / 27 private slices. `python -X utf8 scripts/verify-rb12.py` is read-only against originals/DB and writes only mission verification metadata. `rb12-acquire.py acquire` skips already listed URLs and never overwrites changed original bytes.
3. Separate source authors, compiler, historical editor, modern transcriber, anonymous continuator, quoted letter writer and publisher advertisement. Keep the explicit old-style 1659/60 year and source lacunae. Do not infer a primary author's precise date from an edition year or chapter period.
4. Rights: TCP CC0 text is a stronger explicit permission witness; publisher images are excluded. 1847/1811/1851 historical underlying works are distinct from modern web editions. Hayden copyright and TGC rights remain held. On the Wing explicitly grants personal use and states restrictions; retain the unmodified edition and assess downstream extraction/index use separately.
5. OCR text already existed at the source; no OCR jobs, scan/PDF rendering or image assets were generated. Quality checks are structural. Preserve corrupt readings; quarantine uncertain names/dates/quotations rather than asking an LLM to repair history. Image-only Philadelphia tables remain out of scope.
6. Exclude duplicate RB07 text; reuse every mapped witness and source locus. Philadelphia 1777 repeated editorial notices are one historical assertion, not separate meeting documents. Do not blend the two Broadmead editions or treat shared confession material as wholly new text.
7. Review [RELATIONSHIPS.md](RELATIONSHIPS.md) before any graph work. Its rows are source assertions or attributed historical arguments, not graph edges; confidence, temporal bounds and author/editor roles must survive later enrichment.
8. Preserve the post-RB14 aggregate ingestion/vector/graph/enrichment gate, existing scheduler and watchdog. Do not launch RB13 or a DB worker from this report. Formal catalog promotion waits for sufficient identity, rights and editorial evidence; private bodies stay outside Git/public hosting.
''')
    write('source-exceptions.json',dict(mission='RB12',decisions=[
      dict(candidate='Michigan persistent TCP endpoints',urls=['https://name.umdl.umich.edu/A47565.0001.001','https://name.umdl.umich.edu/A88025.0001.001'],state='403 on institutional offer',action='Independent official TCP repositories offer the exact identified XML with embedded CC0; acquired through their listed public download URLs. No authentication/access restriction bypass.'),
      dict(candidate='Baptist Studies Online',url='https://baptiststudiesonline.com/',state='TLS certificate validation failure',action='No certificate disabling or HTTP fallback. Continue other legitimate repositories.'),
      dict(candidate='Themelios source policy',url='https://www.thegospelcoalition.org/robots.txt',state='600-second crawl delay',action='Respected publisher spacing for essay and foundation evidence. Incorrect guessed about-themelios route returned 404; no further retries.'),
      dict(candidate='On the Wing Library.html',url='https://www.onthewing.org/user/Library.html',state='404 discovery route',action='Actual home page links Classics.html; exact offered Kiffin PDF and Copyright.html verified.'),
      dict(candidate='Ivimey volumes II-IV and full Gill treatise',url='https://www.reformedreader.org/history/ivimey/volume1/contents.htm',state='other volumes/full Gill treatise outside selected first-volume components',action='Do not claim four-volume completeness or count Gill as Ivimey. The prefixed extract is now acquired; a whole Gill treatise remains a separate completeness question, not filled by the excerpt.'),
      dict(candidate='1689 General Assembly narrative',url='https://theangus.rpc.ox.ac.uk/treasures/a-narrative-of-the-proceedings-of-the-general-assembly-of-divers-pastors-messengers-and-ministring-brethren-of-the-baptized-churches-met-together-in-london/',state='institution offers two PDF parts; extractible-text status not verified',action='Metadata discovery only; no PDF/image acquired and no OCR. Resume with one bounded text-layer check only if a permitted neat PDF is necessary; otherwise leave noted.'),
      dict(candidate='Renihan Faith & Life for Baptists 1689-1694',url='https://www.solid-ground-books.com/detail_147.asp',state='commercial book and table of contents; no authorized full readable offer found',action='Keep missing assembly narratives and supporting letters as priorities. Confession/catechism already held do not fill the narrative gap. No preview or unauthorized copy acquired.'),
      dict(candidate='Philadelphia image-only statistics',state='text pages reference statistical JPGs',action='Image URLs recorded in selected-text-review.json only; no download, imaging, transcription or inferred statistics. Readable narrative acquisition is not completeness of non-text tables.'),
      dict(candidate='Crosby, early British association records and later Ivimey volumes',state='not acquired in this bounded mission',action='Next historical run should first audit all current manifests, then prioritize clean complete primary association/correspondence texts over another general-history scan collection.')]))
    # Record doctrinal/edition evidence actually read, beyond initial audit snapshot.
    additional=[]
    for name in ['theological-evidence.json','source-exceptions.json','relationship-table.json']:
        p=R/name;additional.append(dict(path=p.relative_to(SITE).as_posix(),sha256=sha(p.read_bytes()),byteCount=p.stat().st_size))
    write('review-inputs.json',dict(mission='RB12',additionalReadEvidence=additional,initialInputCount=len(read('input-audit.json'))))
    # Documents only; REPORT.md is intentionally not written here.
    common='**46 originals / 5.24 MB / 709,313 extracted words:** seven historical work/collection groups, eight edition witnesses. Ivimey Volume I, selected Philadelphia association records/circulars, Broadmead 1847 and 1974 TXT, Kiffin autobiography, Knollys life/legacy, joint London letter and Belyea origins study. Reused 51 held witnesses including all eleven RB07 mapped witnesses and the confessional spine. 98 actual relevant originals and 13,110 prior ledger records audited/screened. 97 mapped witnesses / 490 source locations / 194 historical document rows / 27 exact private components / 13 qualified relationship rows. Not 46 new books, not all Philadelphia century records, and no graph assertions.'
    def insert(path,label,body):
        text=path.read_text('utf-8');block='<!-- RB12 '+label+' -->\n'+body.strip()+'\n<!-- /RB12 '+label+' -->\n'
        pat=r'<!-- RB12 '+re.escape(label)+r' -->.*?<!-- /RB12 '+re.escape(label)+r' -->\n?'
        if re.search(pat,text,re.S):text=re.sub(pat,lambda _:block,text,flags=re.S)
        else:
            at=text.find('\n')+1;text=text[:at]+'\n'+block+'\n'+text[at:]
        path.write_text(text,encoding='utf-8',newline='\n')
    links='[Report](reports/reformed-baptist-overnight/RB12/REPORT.md), [document table](reports/reformed-baptist-overnight/RB12/DOCUMENT-TABLE.md), [reading paths](reports/reformed-baptist-overnight/RB12/READING-MAP.md), [relationships](reports/reformed-baptist-overnight/RB12/RELATIONSHIPS.md), [scope](reports/reformed-baptist-overnight/RB12/THEOLOGICAL-SCOPE.md), [checkpoint](reports/reformed-baptist-overnight/RB12/checkpoint.json).'
    insert(SITE/'content/library/BACKLOG.md','backlog','## 2026-10-07: RB12 Baptist historical evidence acquired\n\n'+common+'\n\n'+links+'\n\nAll new parents/slices evidence-only, not ingested/embedded. Formal catalog unchanged pending identity/editorial/rights review; sources are documented in SOURCES. No OCR/images or worker/scheduler/watchdog changes. Post-RB14 gate remains; RB13 only when prompted.')
    insert(SITE/'content/library/REFORMED-BAPTIST-ACQUISITION.md','protocol','## 2026-10-07: RB12 historical documents mission complete\n\nOwner-added RB12 applies the shared protocol to Particular/Reformed Baptist origins, churches, associations, confessions and doctrinal development, prioritizing primary records. Historical evidence is distinct from theological endorsement.\n\n'+common+'\n\n'+links+'\n\nText only; no scans, images, new OCR, transcription or media. All parents and exact private samples held for post-RB14 aggregate intake. Do not launch another mission or database/vector/graph/enrichment worker automatically.')
    site_links=links.replace('](reports/','](content/library/reports/')
    insert(SITE/'README.md','readme','## RB12: Baptist historical evidence\n\n'+common+'\n\n'+site_links+'\n\nImmutable private text originals and source-located tables are ready for review. Historical claims, editors and uncertain dates stay explicit. No DB/vector/graph/enrichment launch; post-RB14 intake gate unchanged.')
    sources=['## RB12: Baptist origins, churches, associations and historical evidence (7 October 2026)','',''+common,'','[Acquisition manifest](content/library/reports/reformed-baptist-overnight/RB12/acquisition-manifest.json) records every original, retrieval date, final URL, SHA-256, edition and private derivative. [Historical document table](content/library/reports/reformed-baptist-overnight/RB12/DOCUMENT-TABLE.md), [edition limits](content/library/reports/reformed-baptist-overnight/RB12/COVERAGE.md), [scope](content/library/reports/reformed-baptist-overnight/RB12/THEOLOGICAL-SCOPE.md), [checkpoint](content/library/reports/reformed-baptist-overnight/RB12/checkpoint.json).','', 'Every acquired text offer is listed below. These missions authorize private acquisition, not public full-text hosting. Modern editor/edition/repository rights remain distinct from historical underlying text.','']
    for a in new:sources.append('- ['+a['title'].replace('\n',' ')+']('+a['url']+'). '+a['author']+'. '+a['edition']+' '+a['completeness']+' Rights: '+a['rightsEvidence'])
    sources+=['','Permission/identity evidence: [On the Wing copyright notice](https://www.onthewing.org/Copyright.html), [Bristol Record Society official distribution statement](https://bristolrecordsociety.org/publications/bristol-record-society-publications/), [TCP Knollys repository](https://github.com/textcreationpartnership/A47565), [TCP letter repository](https://github.com/textcreationpartnership/A88025), [TGC foundation documents](https://www.thegospelcoalition.org/about/foundation-documents/). TCP XML explicitly includes CC0 text dedication; no associated page images acquired. Other modern rights are held for corpus review.','', 'Known limits: Philadelphia statistical images excluded; 1777 is an editorial no-meeting note; Knollys own later manuscript missing; Ivimey only Volume I with separately authored Gill prefixed excerpt and disputed ancestry claims; two Broadmead editions overlap. Historical and modern contributor roles remain separate; repositories are not globally approved. All 46 original parents / 27 slices not ingested or embedded; no DB or worker changes.']
    insert(SITE/'SOURCES.md','sources','\n'.join(sources))
    parent_links=site_links.replace('](content/','](Website/content/')
    for filename,label in [('TODO.md','todo'),('HANDOFF.md','handoff')]:
        insert(SITE.parent/filename,label,'## 2026-10-07: RB12 historical evidence acquired and mapped\n\n'+common+'\n\n'+parent_links+'\n\n- [x] Acquire and hash reviewed missing historical text; document every offer in Website/SOURCES.md.\n- [x] Reuse RB07 and confession witnesses; separate author/editor/uncertain historical claims and image-only statistics.\n- [ ] Post-RB14 aggregate reconciliation: rights, identities, contributor boundaries and exact corpus delta; then dedicated authorized import/vector parity.\n\nAll parents/slices evidence-only, not ingested/embedded. No new scans/images/OCR/media/transcription; DB/vector/graph/enrichment and scheduler/watchdog unchanged. Next mission only on explicit owner prompt. Private bodies excluded from Git; local mission metadata only; no push attempted.')
    print('DOCUMENTED source offers, ten reading paths, thirteen relationships, scope, coverage and project handoff; report intentionally deferred')
if __name__=='__main__':main()
