// Writes CONTENT.md for every major page (Study, Atlas, Topics, Apologetics, and the Site pages: home, reader, search…) into the project's Pages/ folder,
// generated from the same data the site uses. Never edit those files by hand: change the data and rerun.
//   bun run pages:content                 -> ../Pages/<Area>/<page>/CONTENT.md
//   bun run pages:content -- --out <dir>  -> somewhere else (for a dry run)
// Only CONTENT.md is ever written; README.md and HANDOFF.md beside it are hand-maintained.
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Extractor, PageContent } from "./pages/types";

const root = path.resolve(import.meta.dirname, "..");
const outFlag = process.argv.indexOf("--out");
const out = path.resolve(outFlag > -1 ? process.argv[outFlag + 1] : path.join(root, "..", "Pages"));
const DIR = /^(Study|Atlas|Topics|Apologetics|Site)(\/[a-z0-9]+(-[a-z0-9]+)*){0,2}$/;

const areas: Record<string, () => Promise<{ extract: Extractor }>> = {
  Study: () => import("./pages/study"),
  Atlas: () => import("./pages/atlas"),
  Topics: () => import("./pages/topics"),
  Apologetics: () => import("./pages/apologetics"),
  Site: () => import("./pages/site"),
};

const render = (page: PageContent) =>
  [
    `# ${page.title}: content`,
    "",
    "> Generated by `bun run pages:content` (Website/scripts/export-pages.ts) from the site's own data.",
    "> Do not edit by hand: change the data and rerun. The page's notes are in README.md and HANDOFF.md beside this file.",
    "",
    page.markdown.replace(/\r\n/g, "\n").trim(),
    "",
  ].join("\n");

async function existingContentFiles(dir: string, found: string[] = []): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch((error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return [];
    throw error;
  });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) await existingContentFiles(full, found);
    else if (entry.name === "CONTENT.md") found.push(path.relative(out, path.dirname(full)).split(path.sep).join("/"));
  }
  return found;
}

const written = new Set<string>();
let changed = 0;
const failures: string[] = [];
for (const [area, load] of Object.entries(areas)) {
  let pages: PageContent[];
  try {
    pages = await (await load()).extract();
  } catch (error) {
    failures.push(`${area}: extractor failed: ${(error as Error).stack ?? error}`);
    continue;
  }
  for (const page of pages) {
    if (!DIR.test(page.dir) || !page.dir.startsWith(area)) {
      failures.push(`${area}: refused folder "${page.dir}" (expected ${area}/<kebab-case>[/<kebab-case>])`);
      continue;
    }
    if (written.has(page.dir)) {
      failures.push(`${area}: two pages share the folder "${page.dir}"`);
      continue;
    }
    written.add(page.dir);
    const file = path.join(out, ...page.dir.split("/"), "CONTENT.md");
    const text = render(page);
    const before = await readFile(file, "utf8").catch(() => null);
    if (before === text) continue;
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, text, "utf8");
    changed += 1;
  }
}

const orphans = (await existingContentFiles(out)).filter((dir) => !written.has(dir)).sort();
console.log(`Pages content: ${written.size} pages, ${changed} changed, written under ${out}`);
if (orphans.length) console.log(`No longer generated (left in place, review by hand):\n  ${orphans.join("\n  ")}`);
if (failures.length) {
  console.error(`\n${failures.length} problem(s):\n${failures.join("\n")}`);
  process.exit(1);
}
