import { readFileSync } from 'node:fs';

export function missionGeographySection(): string {
  const snapshot = JSON.parse(readFileSync('content/missions/muslim-world.json', 'utf8'));
  return [
    '## Islam: An atlas for understanding the Muslim world', '',
    'A world of people. Learn the place. A globe and a flat SVG map use faded deep-blue oceans and continuous deep-green/brown terrain washes with subtle country outlines, and open the same country profiles without Earth imagery or WebGL textures. Terrain colours flow across national borders and are illustrative, independent of demographics or engagement classifications. Original country outline and marker styling is restored; ocean and terrain lightness is reduced a further 20% from the Earth-only palette, retaining saturation. The thin globe outline follows the physical Earth at each zoom. Colour stays inside the Earth; the surrounding area uses the page background, without a circular crop or framing glow. A vertical pair of globe/map icons in the upper-right of the map switches views. Country selection is shareable with `?country=<IMB-code>#muslim-world` and preserves the selected comparison question.', '',
    `Scope: ${snapshot.scope} ${snapshot.countries.length} countries and territories. Demographic year: ${snapshot.demographicYear}. IMB snapshot: ${snapshot.snapshotDate}.`, '',
    'Country panel: the adopted B header shows a larger local flag, searchable country selection, and adjacent Population, Muslim and Christian facts. C Gospel Presence cards open the B editorial People Groups rows filtered to the clicked engagement category. Every active IMB group remains available through search, count-bearing engagement filters and All groups, with exact population, language, religion and status. Only the selected country table loads when opened. panel=groups and engagement preserve the selected view in shared links. The source links and external pill-only scroll thumb remain available. Review options are shown only through explicit atlasDesign links.', '',
    'Map: worldwide coastlines, with country outlines only where Pew estimates at least 20% Muslim identification in 2020. All 61 qualifying countries and territories have outlines; the 53 Muslim-majority profiles are selectable. Benin, Cameroon, Cyprus, Ethiopia, Ivory Coast, Montenegro, North Macedonia and Tanzania are outlined without selectable profiles. A rectangular viewport fills the map column. The initial globe scale is 1.35x; Home or zooming fully out shows the round Earth at 1x. Wheel gestures enlarge geography to 8x across the rectangle; scrolling stays contained at both limits. Arrow keys turn it, Space pauses/starts rotation, and Home resets. Phones and coarse-pointer devices start with rotation paused. Only the two view icons are shown; there are no zoom or rotation buttons. The flat map supports wheel zoom and drag/arrow-key panning, preserves country selection and reuses the already-loaded geography.', '',
    'Country panel review: eight transplantable options A-H are available through atlasDesign=a|b|c|d|e|f|g|h on the existing Islam page. The review picker sits outside and above the atlas. People Groups layouts are reading ledger, editorial rows, engagement chapters, open directory, group focus, language index, comparison matrix and field notes. They use the website theme colours and complete lazy country snapshots. Panel A uses a larger flag left of the name, region underneath, population on the right, and separately labelled proportional Muslim/Christian bars.', '',
    'IMB counts cover all people groups in each country, including non-Muslim groups. No longer unreached is not a country completion score. Country aggregates preserve the source Engagement Progress categories; see content/missions/README.md for definitions, provenance and refresh steps.', '',
    `Sources: [Pew Research Center](${snapshot.sources.pew.url}), [IMB Global Research](${snapshot.sources.imb.url}). Coastlines and country outlines: Natural Earth (public domain).`, '',
    '| Country / territory | Population estimate (2020) | Muslim identification (2020) | IMB groups | Unengaged & unreached | Engaged yet unreached | No longer unreached |',
    '|---|---:|---:|---:|---:|---:|---:|',
    ...snapshot.countries.map((country: { name: string; population2020: number; muslimShare2020: number; imb: { totalGroups: number; unengaged: { groups: number }; engagedUnreached: { groups: number }; noLongerUnreached: { groups: number } } }) =>
      `| ${country.name} | ${country.population2020.toLocaleString('en')} | ${country.muslimShare2020.toFixed(1)}% | ${country.imb.totalGroups} | ${country.imb.unengaged.groups} | ${country.imb.engagedUnreached.groups} | ${country.imb.noLongerUnreached.groups} |`),
  ].join('\n');
}
