// The design review board's data (content/design-review/, served only by the local preview: scripts/design-review/
// vite-plugin.ts). Generated by scripts/design-review/: inventory.ts (templates), shots.mjs (screenshots), checks.mjs
// (machine checks). Decisions are written by the board itself, from the owner's clicks.

export interface Sample { id: string; label: string; url: string; why: string }
export interface Variant { id: string; name: string; what: string; instances: number; samples: Sample[] }
export interface Template {
  id: string;
  area: string;
  name: string;
  what: string;
  address: string;
  instances: number;
  sources: string[];
  sourceHash: string;
  signature: { selector: string; label: string } | null;
  variants: Variant[];
}
export interface Inventory { schema: 1; generatedAt: string; commit: string; areas: { id: string; title: string }[]; templates: Template[] }

export interface ShotView { full: string; crop: string | null; cropKind?: "signature" | "first-screen"; thumb: string; hash: string; height: number; clipped: boolean }
export interface ShotManifest { schema: 1; commit: string; takenAt: string; base: string; images: Record<string, Partial<Record<ViewKey, ShotView>>> }

export interface CheckFailure { url: string; width: number; check: string; detail: string }
export interface CheckResult {
  template: string;
  variant: string;
  instances: number;
  checked: number;
  coverage: string;
  failed: Record<string, number>;
  failures: CheckFailure[];
}
export interface CheckFile { schema: 1; commit: string; startedAt: string; finishedAt: string | null; base: string; checks: { id: string; name: string }[]; results: CheckResult[] }

export interface Decision {
  id: string;
  template: string;
  variant: string;
  viewport: "all" | "desktop" | "phone";
  theme: "all" | "light" | "dark";
  status: "accepted" | "needs-changes";
  note: string;
  at: string;
  commit: string;
  sourceHash: string;
  shotHashes: Record<string, string>;
}
export interface DecisionFile { schema: 1; note: string; decisions: Decision[] }

export type ViewKey = "desktop-light" | "desktop-dark" | "phone-light" | "phone-dark";
export const VIEWS: { key: ViewKey; width: "desktop" | "phone"; theme: "light" | "dark"; label: string }[] = [
  { key: "desktop-light", width: "desktop", theme: "light", label: "Desktop · light" },
  { key: "desktop-dark", width: "desktop", theme: "dark", label: "Desktop · dark" },
  { key: "phone-light", width: "phone", theme: "light", label: "Phone · light" },
  { key: "phone-dark", width: "phone", theme: "dark", label: "Phone · dark" },
];

export type Status = "not-reviewed" | "accepted" | "needs-changes" | "changed";
export const STATUS_WORDS: Record<Status, string> = {
  "not-reviewed": "Not reviewed",
  accepted: "Accepted",
  "needs-changes": "Needs changes",
  changed: "Changed since accepted",
};

/** Two perceptual hashes (16 hex digits = 64 bits) count as the same picture when at most this many bits differ. */
const SAME_PICTURE_BITS = 6;

export function hashDistance(a: string, b: string): number {
  if (a.length !== b.length) return 64;
  let bits = 0;
  for (let i = 0; i < a.length; i++) {
    let x = parseInt(a[i], 16) ^ parseInt(b[i], 16);
    while (x) { bits += x & 1; x >>= 1; }
  }
  return bits;
}

const covers = (d: Decision, view: (typeof VIEWS)[number]) => (d.viewport === "all" || d.viewport === view.width) && (d.theme === "all" || d.theme === view.theme);

/** Every screenshot hash of a variant for one view, keyed "<sample>/<view>" (what a decision is recorded against). */
export function viewHashes(shots: ShotManifest | null, template: Template, variant: Variant, views: ViewKey[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const sample of variant.samples) {
    const images = shots?.images[`${template.id}/${variant.id}/${sample.id}`];
    for (const view of views) { const hash = images?.[view]?.hash; if (hash) out[`${sample.id}/${view}`] = hash; }
  }
  return out;
}

/** One view's status: its newest decision, demoted to "changed" when the template's code or its screenshots moved. */
export function viewStatus(decisions: Decision[], shots: ShotManifest | null, template: Template, variant: Variant, view: (typeof VIEWS)[number]): { status: Status; decision?: Decision; why?: string } {
  const latest = decisions.filter((d) => d.template === template.id && d.variant === variant.id && covers(d, view)).sort((a, b) => a.at.localeCompare(b.at)).at(-1);
  if (!latest) return { status: "not-reviewed" };
  if (latest.status === "needs-changes") return { status: "needs-changes", decision: latest };
  if (latest.sourceHash && latest.sourceHash !== template.sourceHash) return { status: "changed", decision: latest, why: "the page's code changed after it was accepted" };
  const now = viewHashes(shots, template, variant, [view.key]);
  for (const [key, hash] of Object.entries(now)) {
    const then = latest.shotHashes[key];
    if (then && hashDistance(then, hash) > SAME_PICTURE_BITS) return { status: "changed", decision: latest, why: `the screenshot "${key.split("/")[0]}" looks different now` };
  }
  return { status: "accepted", decision: latest };
}

const RANK: Record<Status, number> = { "needs-changes": 0, changed: 1, "not-reviewed": 2, accepted: 3 };

/** A variant's status is its worst view's: one view needing changes means the variant needs changes. */
export function variantStatus(decisions: Decision[], shots: ShotManifest | null, template: Template, variant: Variant): { status: Status; views: Record<ViewKey, ReturnType<typeof viewStatus>> } {
  const views = Object.fromEntries(VIEWS.map((view) => [view.key, viewStatus(decisions, shots, template, variant, view)])) as Record<ViewKey, ReturnType<typeof viewStatus>>;
  const status = Object.values(views).map((v) => v.status).sort((a, b) => RANK[a] - RANK[b])[0];
  return { status, views };
}

/** Fetch one board file; null when it is not there (on the live site the SPA answers every address with HTML). */
export async function loadReviewFile<T>(name: string): Promise<T | null> {
  const response = await fetch(`/review-data/${name}`, { cache: "no-store" });
  if (!response.ok || !(response.headers.get("content-type") ?? "").includes("application/json")) return null;
  return (await response.json()) as T;
}

export async function postDecision(path: "decision" | "undo", body: object): Promise<{ ok?: boolean; error?: string; warning?: string | null; decision?: Decision }> {
  const response = await fetch(`/review-api/${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const type = response.headers.get("content-type") ?? "";
  if (!type.includes("application/json")) return { error: `the local preview did not answer (status ${response.status}); is this the local preview at 127.0.0.1:8931?` };
  return (await response.json()) as { ok?: boolean; error?: string; warning?: string | null; decision?: Decision };
}
