import { afterEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { readFileSync } from "node:fs";
import * as layout from "@/lib/circular-genealogy-auto";
import CircularGenealogyPage from "./CircularGenealogyPage";
import { GenealogyExplorer } from "@/components/study/GenealogyExplorer";

vi.mock("@/components/study/StudyParts",()=>({RefLink:()=>null}));

afterEach(()=>{cleanup();localStorage.clear();vi.restoreAllMocks();vi.unstubAllGlobals();});

it("opens Jesus first and preserves the full Luke account across expand and minimize",async()=>{
  const corpus=JSON.parse(readFileSync("public/content/study/genealogy.json","utf8"));
  vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:async()=>corpus}));
  Object.defineProperty(SVGSVGElement.prototype,"width",{configurable:true,get:()=>({baseVal:{value:1200}})});
  Object.defineProperty(SVGSVGElement.prototype,"height",{configurable:true,get:()=>({baseVal:{value:900}})});
  const screen=render(<MemoryRouter><GenealogyExplorer /></MemoryRouter>);
  const account=await screen.findByRole("combobox",{name:"Gospel genealogy"});
  expect(screen.container.querySelectorAll(".genealogy-node")).toHaveLength(46);
  const families=screen.getByRole("combobox",{name:"All 24 families"}) as HTMLSelectElement;
  expect([...families.options].filter(o=>o.value)).toHaveLength(24);
  expect(families.options[1].text).toBe("Jesus");
  fireEvent.change(account,{target:{value:"luke"}});
  expect(screen.container.querySelectorAll(".genealogy-node")).toHaveLength(76);
  expect(screen.getByRole("spinbutton",{name:"Generations"})).toHaveValue(75);
  fireEvent.click(screen.getByRole("button",{name:"Expand genealogy"}));
  const dialog=await screen.findByRole("dialog",{name:"Expanded genealogy"});
  const controls=within(dialog);
  await controls.findByRole("button",{name:"Minimize"});
  expect(controls.getByRole("combobox",{name:"Gospel genealogy"})).toHaveValue("luke");
  fireEvent.click(controls.getByRole("button",{name:"Circular genealogy view"}));
  expect(dialog.querySelectorAll(".circle-person")).toHaveLength(76);
  for(const node of dialog.querySelectorAll(".circle-person")) expect(node.getAttribute("transform")).not.toMatch(/NaN|Infinity/);
  fireEvent.click(controls.getByRole("button",{name:"Minimize"}));
  await waitFor(()=>expect(screen.queryByRole("dialog",{name:"Expanded genealogy"})).toBeNull());
  expect(screen.getByRole("combobox",{name:"Gospel genealogy"})).toHaveValue("luke");
  expect(screen.container.querySelectorAll(".genealogy-node")).toHaveLength(76);
},15000);

it("expands the real genealogy and minimizes back with its updated family view",async()=>{
  const corpus=JSON.parse(readFileSync("public/content/study/genealogy.json","utf8"));
  vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:async()=>corpus}));
  Object.defineProperty(SVGSVGElement.prototype,"width",{configurable:true,get:()=>({baseVal:{value:1200}})});
  Object.defineProperty(SVGSVGElement.prototype,"height",{configurable:true,get:()=>({baseVal:{value:900}})});
  const screen=render(<MemoryRouter><GenealogyExplorer /></MemoryRouter>);
  const expand=await screen.findByRole("button",{name:"Expand genealogy"});
  expand.focus();fireEvent.click(expand);
  const dialog=await screen.findByRole("dialog",{name:"Expanded genealogy"});
  const controls=within(dialog);
  await controls.findByRole("button",{name:"Family tree view"});
  expect(controls.getByRole("button",{name:"Family tree view"})).toHaveAttribute("aria-pressed","true");
  expect(document.body.style.overflow).toBe("hidden");
  fireEvent.click(controls.getByRole("button",{name:"Jacob / Israel"}));
  fireEvent.change(controls.getByRole("spinbutton",{name:"Generations"}),{target:{value:"6"}});
  fireEvent.click(controls.getByRole("button",{name:"Minimize"}));
  expect(dialog).toHaveClass("is-minimizing");
  await waitFor(()=>expect(screen.queryByRole("dialog",{name:"Expanded genealogy"})).toBeNull());
  expect(screen.getByRole("spinbutton",{name:"Generations"})).toHaveValue(6);
  expect(screen.getByRole("button",{name:"Jacob / Israel"})).toHaveAttribute("aria-pressed","true");
  expect(document.body.style.overflow).not.toBe("hidden");
  expect(expand).toHaveFocus();
},15000);

it("shows two view icons without the editor and opens the same branch as a conventional tree",async()=>{
  const worker={postMessage:vi.fn(),terminate:vi.fn(),onmessage:null,onerror:null};
  vi.stubGlobal("Worker",vi.fn(function(){return worker;}));
  const corpus=JSON.parse(readFileSync("public/content/study/genealogy.json","utf8"));
  vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:async()=>corpus}));
  Object.defineProperty(SVGSVGElement.prototype,"width",{configurable:true,get:()=>({baseVal:{value:1200}})});
  Object.defineProperty(SVGSVGElement.prototype,"height",{configurable:true,get:()=>({baseVal:{value:900}})});
  const screen=render(<MemoryRouter><CircularGenealogyPage familyBands /></MemoryRouter>);
  await waitFor(()=>expect(screen.container.querySelectorAll(".circle-person").length).toBe(430));
  await waitFor(()=>expect(JSON.parse(localStorage.getItem("bible-family-bands-arrangements-v2") ?? "{}")["abraham-gen-11-26:descendants:9"]?.trackLayout).toBe("single-v1"));
  expect(screen.container.querySelector(".circle-editbar")).toBeNull();
  const positions=[...screen.container.querySelectorAll(".circle-person")].map(n=>n.getAttribute("transform"));
  const scene=screen.container.querySelector(".circle-canvas > g")!;
  const camera=scene.getAttribute("transform");
  fireEvent.click(screen.getByRole("button",{name:"Family tree view"}));
  expect(screen.getByRole("region",{name:"Interactive biblical genealogy"})).toBeInTheDocument();
  expect(screen.container.querySelectorAll(".genealogy-node")).toHaveLength(430);
  expect(screen.getByRole("region",{name:"Family tree controls"})).toBeInTheDocument();
  expect(screen.queryByRole("button",{name:"Close person details"})).toBeNull();
  fireEvent.click(screen.getByRole("button",{name:/^Select Jochebed:/}));
  expect(screen.getByRole("complementary",{name:"Jochebed"})).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button",{name:"Close person details"}));
  expect(screen.queryByRole("complementary",{name:"Jochebed"})).toBeNull();
  fireEvent.click(screen.getByRole("button",{name:/^Select Jochebed:/}));
  fireEvent.keyDown(screen.getByRole("complementary",{name:"Jochebed"}),{key:"Escape"});
  expect(screen.queryByRole("button",{name:"Close person details"})).toBeNull();
  expect(screen.getByRole("spinbutton",{name:"Generations"})).toHaveValue(9);
  expect(worker.postMessage).not.toHaveBeenCalled();
  expect(screen.container.querySelectorAll(".genealogy-continuation")).toHaveLength(4);
  const marker=screen.container.querySelector(".genealogy-continuation")!;
  fireEvent.click(marker);
  expect(marker).toHaveAttribute("aria-pressed","true");
  const stems=screen.container.querySelectorAll(".genealogy-edge-parent");
  expect(stems.length).toBeGreaterThan(0);
  expect(stems.length).toBeLessThan(250);
  for(const line of screen.container.querySelectorAll(".genealogy-edge")) expect(line.getAttribute("d")).toMatch(/^M[-\d.,]+ L[-\d.,]+$/);
  expect(screen.getByRole("button",{name:"Family tree view"})).toHaveAttribute("aria-pressed","true");
  fireEvent.click(screen.getByRole("button",{name:"Circular genealogy view"}));
  expect(screen.container.querySelector(".genealogy-fullscreen")).toBeNull();
  expect(worker.terminate).not.toHaveBeenCalled();
  expect([...screen.container.querySelectorAll(".circle-person")].map(n=>n.getAttribute("transform"))).toEqual(positions);
  expect(scene.getAttribute("transform")).toBe(camera);
});

it("restores pre-spacing offsets at original size, compresses rings and restores their spacing",async()=>{
  const corpus=JSON.parse(readFileSync("public/content/study/genealogy.json","utf8"));
  vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:async()=>corpus}));
  Object.defineProperty(SVGSVGElement.prototype,"width",{configurable:true,get:()=>({baseVal:{value:1200}})});
  Object.defineProperty(SVGSVGElement.prototype,"height",{configurable:true,get:()=>({baseVal:{value:900}})});
  const key="abraham-gen-11-26:descendants:9",storage="bible-family-bands-arrangements-v2";
  const initial=render(<MemoryRouter><CircularGenealogyPage editing familyBands /></MemoryRouter>);
  await waitFor(()=>expect(JSON.parse(localStorage.getItem(storage) ?? "{}")[key]?.trackLayout).toBe("single-v1"));
  const previous=JSON.parse(localStorage.getItem(storage)!)[key];
  initial.unmount();
  const enlarged={...previous,spacingPass:"2x-v1",offsets:{"isaac-gen-17-19":.2}};
  localStorage.setItem(storage,JSON.stringify({[key]:enlarged}));
  localStorage.setItem("bible-family-bands-smooth-2x-checkpoints-v1",JSON.stringify({[key]:{at:"test",arrangement:previous}}));
  const screen=render(<MemoryRouter><CircularGenealogyPage editing familyBands /></MemoryRouter>);
  await waitFor(()=>expect(screen.container.querySelectorAll(".circle-person").length).toBe(430));
  const current=()=>JSON.parse(localStorage.getItem(storage)!)[key];
  expect(current().offsets).toEqual(previous.offsets);
  expect(JSON.parse(localStorage.getItem(storage+"-before-ring-compression")!)[key]).toEqual(enlarged);
  const circles=()=>[...screen.container.querySelectorAll(".circle-person circle")].map(n=>n.getAttribute("r"));
  expect(circles().every(r=>r==="27" || r==="40")).toBe(true);
  const scene=screen.container.querySelector(".circle-canvas > g")!;
  const camera=scene.getAttribute("transform");
  const ringRadii=()=>[...screen.container.querySelectorAll(".circle-ring-hit")].map(n=>Number(n.getAttribute("r")));
  const originalRadii=ringRadii();
  fireEvent.change(screen.getByLabelText("Bring rings closer"),{target:{value:"100"}});
  expect(ringRadii().some((r,i)=>r<originalRadii[i])).toBe(true);
  expect(current().offsets).not.toEqual(previous.offsets);
  const packedRadii=ringRadii();
  expect(packedRadii.at(-1)!).toBeLessThan(originalRadii.at(-1)!*.65);
  const widths=[92,160,180,260,260,260,260,260,260].map((width,i)=>current().ringWidths?.[i+1] ?? width);
  packedRadii.slice(1).forEach((r,i)=>expect(r-packedRadii[i]-widths[i]/2-widths[i+1]/2).toBeCloseTo(12,6));
  expect(packedRadii.at(-1)!-packedRadii.at(-2)!).toBeCloseTo(packedRadii[2]-packedRadii[1],6);
  expect(packedRadii.at(-1)!-packedRadii.at(-2)!).toBeCloseTo(92,6);
  expect(scene.getAttribute("transform")).toBe(camera);
  expect(circles().every(r=>r==="27" || r==="40")).toBe(true);
  const positions=[...screen.container.querySelectorAll(".circle-person")].map(n=>{
    const [x,y]=n.getAttribute("transform")!.match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi)!.map(Number);
    return {x,y,r:Number(n.querySelector("circle")!.getAttribute("r"))};
  });
  for(let i=0;i<positions.length;i++) for(let j=0;j<i;j++) expect(Math.hypot(positions[i].x-positions[j].x,positions[i].y-positions[j].y)).toBeGreaterThanOrEqual(positions[i].r+positions[j].r+9.99);
  fireEvent.change(screen.getByLabelText("Bring rings closer"),{target:{value:"0"}});
  ringRadii().forEach((r,i)=>expect(r).toBeCloseTo(originalRadii[i],8));
  fireEvent.change(screen.getByLabelText("Bring rings closer"),{target:{value:"100"}});
  fireEvent.click(screen.getByRole("button",{name:"Restore saved spot"}));
  expect(current().offsets).toEqual(previous.offsets);
  screen.unmount();
  const reloaded=render(<MemoryRouter><CircularGenealogyPage editing familyBands /></MemoryRouter>);
  await waitFor(()=>expect(reloaded.getByLabelText("Bring rings closer")).toHaveValue("0"));
  expect(current().offsets).toEqual(previous.offsets);
});

it("converts saved tracks once, keeps ring radii and size, and allows Undo without reconversion",async()=> {
  const corpus=JSON.parse(readFileSync("public/content/study/genealogy.json","utf8"));
  vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:async()=>corpus}));
  Object.defineProperty(SVGSVGElement.prototype,"width",{configurable:true,get:()=>({baseVal:{value:1200}})});
  Object.defineProperty(SVGSVGElement.prototype,"height",{configurable:true,get:()=>({baseVal:{value:900}})});
  const arrange=vi.spyOn(layout,"arrangeCircularFamilies");
  const key="abraham-gen-11-26:descendants:9";
  const previous={scale:3,offsets:{},spacingPass:"2x-v1",ringTracks:{3:3,4:3,5:3,6:3,7:3,8:3,9:3}};
  localStorage.setItem("bible-family-bands-arrangements-v2",JSON.stringify({[key]:previous}));
  const screen=render(<MemoryRouter><CircularGenealogyPage editing familyBands sizeScale={2} /></MemoryRouter>);
  await waitFor(()=>expect(screen.container.querySelectorAll(".circle-person").length).toBe(430));
  await waitFor(()=>expect(JSON.parse(localStorage.getItem("bible-family-bands-arrangements-v2")!)[key].trackLayout).toBe("single-v1"));
  const saved=JSON.parse(localStorage.getItem("bible-family-bands-arrangements-v2")!)[key];
  expect(saved.scale).toBe(previous.scale);
  expect(saved.ringScales).toBeUndefined();
  expect(Object.values(saved.ringTracks).every(n=>n===1)).toBe(true);
  expect(arrange).not.toHaveBeenCalled();
  for(const person of screen.container.querySelectorAll(".circle-person")) expect(person.querySelector("circle")).toHaveAttribute("r",person.getAttribute("data-generation")==="0" ? "80" : "54");
  fireEvent.click(screen.getByRole("button",{name:"Undo"}));
  const restored=JSON.parse(localStorage.getItem("bible-family-bands-arrangements-v2")!)[key];
  expect(restored).toEqual({...previous,trackLayout:"single-v1",originalSizeRestored:true});
  expect(screen.getByRole("button",{name:"Undo"})).toBeDisabled();
  expect(arrange).not.toHaveBeenCalled();
});

it("doubles visible sizes without changing saved coordinates, ring radii or viewport",async()=>{
  const corpus=JSON.parse(readFileSync("public/content/study/genealogy.json","utf8"));
  vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:async()=>corpus}));
  Object.defineProperty(SVGSVGElement.prototype,"width",{configurable:true,get:()=>({baseVal:{value:1200}})});
  Object.defineProperty(SVGSVGElement.prototype,"height",{configurable:true,get:()=>({baseVal:{value:900}})});
  const arrange=vi.spyOn(layout,"arrangeCircularFamilies");
  const saved={scale:3,personRadius:216,offsets:{"isaac-gen-17-19":.27},layoutRevision:3};
  const original={scale:3,offsets:{"isaac-gen-17-19":.16},trackLayout:"single-v1",spacingPass:"2x-v1"};
  localStorage.setItem("bible-family-bands-layout-study-v2",JSON.stringify({baselines:{},notes:"",discardedEvents:0,events:[{view:"abraham-gen-11-26:descendants:9",before:original,after:saved}]}));
  localStorage.setItem("bible-family-bands-arrangements-v2",JSON.stringify({"abraham-gen-11-26:descendants:9":saved}));
  const screen=render(<MemoryRouter><CircularGenealogyPage editing familyBands sizeScale={1} /></MemoryRouter>);
  await waitFor(()=>expect(screen.container.querySelectorAll(".circle-person").length).toBe(430));
  const person=screen.container.querySelector('[data-person-id="isaac-gen-17-19"]')!;
  const scene=screen.container.querySelector(".circle-canvas > g")!;
  const positions=[...screen.container.querySelectorAll(".circle-person")].map(n=>n.getAttribute("transform"));
  const viewport=scene.getAttribute("transform");
  const rings=[...screen.container.querySelectorAll(".circle-ring-hit")].map(n=>n.getAttribute("r"));
  expect(person.querySelector("circle")).toHaveAttribute("r","27");
  screen.rerender(<MemoryRouter><CircularGenealogyPage editing familyBands sizeScale={2} /></MemoryRouter>);
  expect(person.querySelector("circle")).toHaveAttribute("r","54");
  expect(person.querySelector("text")).toHaveAttribute("font-size","20");
  expect(scene.getAttribute("transform")).toBe(viewport);
  expect([...screen.container.querySelectorAll(".circle-ring-hit")].map(n=>n.getAttribute("r"))).toEqual(rings);
  fireEvent.mouseEnter(person);
  for(let i=0;i<20;i++){fireEvent.mouseEnter(person);fireEvent.mouseLeave(person);}
  expect(arrange).not.toHaveBeenCalled();
  expect(scene.getAttribute("transform")).toBe(viewport);
  const mouse=(type:string,clientX:number,clientY:number)=> {
    const event=new MouseEvent(type,{bubbles:true,button:2,buttons:type==="mouseup" ? 0 : 2,clientX,clientY});
    Object.defineProperty(event,"view",{value:window});
    return event;
  };
  fireEvent(person,mouse("mousedown",400,300));
  fireEvent(window,mouse("mousemove",480,340));
  fireEvent(window,mouse("mouseup",480,340));
  expect(scene.getAttribute("transform")).not.toBe(viewport);
  expect([...screen.container.querySelectorAll(".circle-person")].map(n=>n.getAttribute("transform"))).toEqual(positions);
  expect(person.querySelector("circle")).toHaveAttribute("r","54");
  expect(JSON.parse(localStorage.getItem("bible-family-bands-arrangements-v2")!)["abraham-gen-11-26:descendants:9"]).toEqual(original);
  expect(JSON.parse(localStorage.getItem("bible-family-bands-arrangements-v2-before-size-rollback")!)["abraham-gen-11-26:descendants:9"]).toEqual(saved);
});
